### ISSUE TITLE
Simplifier le chargement des données OCS GE

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#188]
- Supprimer les foreign key
- Pre-calculer les champs calculés
- Supprimer les labels
- Ajouter les champs arbitraires avant le chargement
- Supprimer les champs inutilisés

## Occupation du sol

- foreign key : `matrix`, `departement`
- champs calculés : `surface`
- supprimer les labels :  `couverture_label`, `usage_label`
- champs arbitraires : `year`, `departement` (le renommer en -> `departement_source_id`), `srid_source`

## Différence

- foreign key : `old_matrix`, `new_matrix`, `departement`
- champs calculés : `surface`
- supprimer les labels :  `couverture_label`, `usage_label`
- champs arbitraires : `year_old`, `year_new`,  `srid_source`
- champs inutilisés: `old_is_artif`, `new_is_artif`

## Artificial Area

- foreign key : `departement`
- champs calculés : `surface`
- champs arbitraires : `year`,  `srid_source`

## Zone construite

- foreign key : `departement`
- champs calculés : `surface`
- champs arbitraires : `year`  `srid_source`
- champs inutilisés : `millésime`

**Comment by inesdartiguenave** [comment]
### Explorateur zonages d'urbanisme 

Encart artificialisation par zonage > **détails de l'artificialisation ne se charge pas (tous territoires; toutes mailles)**

![Image](https://github.com/MTES-MCT/sparte/assets/84960477/8a7676ff-a80b-436f-b092-c38925a744c8)

**Comment by alexisig** [comment]
Merci d'avoir trouvé le bug sur l'explorateur des zonages d'urbanisme @inesdartiguenave ! 
Le fix est en chemin (#291)

Pour Airoux, le fait de masquer l'onglet Zonage d'urbanisme et l'encart dans la synthèse c'est quelque chose qu'on vient de rajouter (#266). On a pas mal de territoires avec de l'OCS GE et pas de zone urba

**Comment by inesdartiguenave** [comment]
### Suite recette

**Département Aude** 
Carte artificialisation des communes + explorateur zonage d’urbanisme ne marche pas 

**Département Bas Rhin**
Carte artificialisation des communes + carte artificialisation donne les zones articielles mais pas renaturation et artifcialisation. 

**Département Gers**
Carte comparaison des communes ne marche pas 

**Export EPCI Indre et Loire**
Export word : graphiques qui ne s’affichent pas et tableaux de données qui débordent https://docs.google.com/document/d/15xgXk5hj7z2BPI2wfjcZLUxB3xrMMfGH/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**Téléchargement export ScoT + département**
Pour les SCoT et département latence > 1h donc je vérifierai cet aprem si j'ai le temps

**Comment by inesdartiguenave** [comment]
### Fin de la recette sur les exports 

**Exports non reçus pour ces SCoT et départements**

SCoT : 

- Finistère
- Bas Rhin
- Vaucluse
- Gers
- Isère
- Gers

Département 
- Isère
- Rhone
- Indre et loire 
- Finistère 
- Aude 
- Bas Rhin 
- Vaucluse 
- Gers 

Région : Auvergne Rhone Alpes
