### ISSUE TITLE
Ajouter un export de rapport triennal

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#191]
- [x] Préparer le template avec les variables de template
- [x] Prépare le contexte pour alimenter le template

**Comment by inesdartiguenave** [comment]
- [ ] Proposer un exemple de V1 du rapport local (Google doc)

**Comment by alexisig** [comment]
lie à #237

**Comment by inesdartiguenave** [comment]
Proposition v1 rapport local : https://docs.google.com/document/d/173z6iYFGJEH125NpFZJ0_EbJeSKD8QMk/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**Comment by alexisig** [comment]
Hello @inesdartiguenave, du coup on a profité de l'atelier hier pour discuter du rapport triennal avec @JeremieSeguin  et @smdsgn. Dans l'ensemble il y a pas mal d'informations dans le template, mais il reste des questions en suspens :
- est-ce qu'on ne fait que de la conso dans la V1 (partie 1)
- est-ce qu'on intègre les parties sur la démographie dans la V1 ? (partie 1)
- est-ce qu'on fait l'artif dans la V1 (partie 2)
- Comment on définit l'imperméabilisation au regard de la matrice CS/US (partie 3) ?
- Quelles infos on affiche / n'affiche pas pour les parties qui ne sont pas encore présentes ?
- Dans la partie 2, pourquoi ne pas afficher plus de données qui permettent de comprendre le solde total de l'artif ? Notamment les graphiques "evolution de l'artif par type de couverture et evolution de l'artif par type d'usage" (ceux de l'onglet artif). On pourrait aussi aller plus loin et aussi afficher les graphiques "Evolution de couverture des sols, evolution de l'usage des sols" (ceux de l'onglet découvrir l'ocs ge), avec ou sans tableaux de données.

A mon sens on a les données pour faire quelque chose de bien pour les deux premières parties dès le prochain sprint, mais il faudrait que le document soit entièrement prêt au plus tard dans les premiers jours du prochain sprint, c'est à dire qu'on ait uniquement à remplacer les valeurs / graphiques écrits en dur par des variables de templates.

Pour info, on (surtout @smdsgn) est en train de préparer d'autres US pour accompagner le lancement du rapport triennal, ton retour sur ces propositions serait précieux :  
- #256 
- Un nouvel onglet : https://www.notion.so/Nouvel-onglet-Rapport-local-79eccbcc58ec491d810d32ed4008a21f
- Une landing page : https://www.notion.so/Cr-er-une-landing-page-sp-cifique-au-Rapport-local-3e0562aa61a2478688daa6b7d5286e66

**Comment by inesdartiguenave** [comment]
Mes retours : 

  **est-ce qu'on ne fait que de la conso dans la V1 (partie 1)**
=> Oui uniquement conso en V1

**est-ce qu'on intègre les parties sur la démographie dans la V1 ? (partie 1)**
=> Non on les intégrera une fois améliorées. 

  ** Est-ce qu'on fait l'artif dans la V1 (partie 2)**
=> Non ce sera pour une prochaine itération. 

  ** Comment on définit l'imperméabilisation au regard de la matrice CS/US (partie 3) ?**
=> Cf. réponse d'Anne Laure et on pourra approfondir. 

    **Quelles infos on affiche / n'affiche pas pour les parties qui ne sont pas encore présentes ?**
=> Proposition dans le google doc. 
- On grise dans le sommaire en précisant que ces parties seront bientôt disponible pour les territoires avec l'OCS GE. 
- On affiche le texte d'accompagnement de la DGALN mais pas les graphiques / données. 

    **Dans la partie 2, pourquoi ne pas afficher plus de données qui permettent de comprendre le solde total de l'artif ? Notamment les graphiques "evolution de l'artif par type de couverture et evolution de l'artif par type d'usage" (ceux de l'onglet artif). On pourrait aussi aller plus loin et aussi afficher les graphiques "Evolution de couverture des sols, evolution de l'usage des sols" (ceux de l'onglet découvrir l'ocs ge), avec ou sans tableaux de données.**
=> On approfondit pour une v2

A mon sens on a les données pour faire quelque chose de bien pour les deux premières parties dès le prochain sprint, mais il faudrait que le document soit entièrement prêt au plus tard dans les premiers jours du prochain sprint, c'est à dire qu'on ait uniquement à remplacer les valeurs / graphiques écrits en dur par des variables de template.

**Comment by inesdartiguenave** [comment]
@alexisig @smdsgn La version minimale du rapport local peut contenir uniquement les "indicateurs obligatoires" de la conso d'espaces. Puis les "indicateurs optionnels" (pages 9-12) peuvent être livrés dans un 2ème temps.

**Comment by inesdartiguenave** [comment]
### Recette

Page de garde à la fin : possible de centrer le texte + les logos ?

**Comment by inesdartiguenave** [comment]
@smdsgn @alexisig Quelques retours à intégrer dans l'export du rapport local 🙏

### Retours DGALN 

Sur le doc https://docs.google.com/document/d/173z6iYFGJEH125NpFZJ0_EbJeSKD8QMk/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**1. Objet du rapport local de suivi de l’artificialisation des sols**
MAJ du texte avec les ajouts et suppressions 

**Page finale avec les logos**
MAJ du texte avec les ajouts et suppressions
