### ISSUE TITLE
Envoyer les inscriptions à la newsletter directement dans la base des contacts SendInBlue

### ISSUE THREAD

**Issue by smdsgn** [MTES-MCT/sparte#202]
**Problème :**

- Le formulaire d'inscription à la newsletter ne sauvegarde pas la liste des personnes inscrites sur BREVO mais en BDD sur le site. 
- Aujourd'hui, il n'y a qu'un moyen de s'inscrire à la lettre d'infos (formulaire home page)

DATE_INSCRIPTION_NEWSLETTER : date d'émission du souhait de s'inscrire à la newsletter (OPT-IN) Format DATE
DATE_CONFIRMATION_INSCRIPTION_NEWSLETTER : date de confirmation à l'inscription (DOUBLE OPT-IN) Format DATE 

**Attributs de contacts brevo concernés :**  
EST_INSCRIT_NEWSLETTER : OUI (tout en majuscule), Format texte  carBREVO n'autorise pas la MAJ de  booléens avec un automate zapier
Solutions : 

- Créer des automates brevo (fonction AUTOMATION et pas TRANSACTIONNELS) sur lequel brancher un formulaire jotform (partageable par URL) ✅
- Migrer la double authent' en place actuellement sur les automates BREVO 
- Brancher  le formulaire d'inscription de la Home Page - 
- Décomissionner les tâches transactionnelles car l'automate BREVO INSCRIPTION_NEWSLETTER A pris le relais

----

Segment utilisateurs inscrits à la newsletter: https://app.brevo.com/contact/list/segment/id/11

**Comment by alexisig** [comment]
> Créer des automates brevo (fonction AUTOMATION et pas TRANSACTIONNELS) sur lequel brancher un formulaire jotform (partageable par URL) ✅

@JeremieSeguin est-ce que tu peux définir ce que font ces automates et à quel besoin initial ça répond ?  Est-ce que tu peux également préciser ce qui est entendu par "sur lequel brancher un formulaire jotform" ?

> Migrer la double authent' en place actuellement sur les automates BREVO

Le double opt-in ?

**Comment by JeremieSeguin** [comment]
Alexis, c'est assez compliqué à expliquer à l'écrit. Il y a beaucoup d'éléments sur plusieurs outils.
Je pense que notre point de demain matin sera parfait pour te partager tout ce que je sais sur cette affaire et on gagnera pas mal de temps d'écriture / lecture et aller-retours. 

Si ça te va de procéder comme ça ?

**Comment by alexisig** [comment]
@JeremieSeguin les inscrits à la newsletter sur le site sont directement envoyé à brevo avec #334 

J'ai pas pu faire la partie Jotform car il me manque les autorisations pour éditer le formulaire. Si ça te va, à mon retour de vacances on pourra plugger jotform à notre backend, et avoir le même système de double opt-in partout

**Comment by JeremieSeguin** [comment]
Top, merci ! 

J'ai vu que tu avais fait une mise à jour sur BREVO des personnes inscrites entre février et aujourd'hui, c'est top !
