### ISSUE TITLE
Ajouter un graphique consommation/évolution démographique/évolution des ménages pour le territoire de diag

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#219]
Aujourd'hui, la mise en perspective de la consommation avec l'évolution démographique ou celle du nombre de ménages ne se fait qu'avec les territoires de comparaison. Mais il n'est pas aisé de voir en un seul regard si conso et autres évolutions vont dans le même sens ou pas.

Il faut ajouter sous le bloc "Consommation d'espaces sur le territoire", avant le bloc "Déterminants de la consommation" un graphique représentant les 3 évolutions année après année

Titre du graphique : Profil du territoire

Reprendre les sources dans les blocs idoines et ajouter un tableau avec les 3 infos : conso, évolution de la conso et évolution du nombre de ménages. le tout en pourcentage, la conso par rapport à la surface du territoire, la population et les ménages par rapport à la population et au nombre de ménage total les plus récents disponibles

ne pas montrer dans le graphique les points des années où on n'a pas d'info, comme ci dessous où nos données de ménages ne vont que jusqu'en 2018 et celle de population en 2019

![image(3)](https://github.com/MTES-MCT/sparte/assets/84960477/0cd16c63-ec53-400f-8ea6-9fc254a64c32)

**Comment by alexisig** [comment]
En attente de #426
