### ISSUE TITLE
DTT_Export_Graphique conso annuelle brute

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#223]
Dans l'export Word du diagnostic:
Chapitre 2.1, juste après le graphique
Ajouter une ligne avec "L'ordre d'empilement est le même que celui de la légende."

![image(4)](https://github.com/MTES-MCT/sparte/assets/84960477/42520cf9-a15c-483b-819b-e5482aeaa6ce)

**Comment by alexisig** [comment]
Pour le diagnostic en ligne, US lié : #239

**Comment by alexisig** [comment]
Le graphique a été modifié, je ferme l'issue
