### ISSUE TITLE
Nouvelle méthode calcul de l'artificialisation

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#228]
[US ClickUp](https://app.clickup.com/t/8693w1unr)

Nouveau mode de faire tenant compte des seuils du décret du 27 novembre 2023

Sur ce lien, la fiche technique, le mode de faire sur QGIS et le mode de faire sur POSTGIS :

https://artificialisation.developpement-durable.gouv.fr/mesurer-lartificialisation-avec-locsge/acceder-aux-analyses-realisees-partir-des-donnees-ocsge

On doit calculer les couches d'artificialisation pour tous les millésimes mais aussi avoir une sélection des objets de l'OCS GE qui sont dans ces espaces pour le croisement avec les DU en particulier mais aussi pour expliquer l'artif

----

Contraintes liées à la modification du calcul :

- ne plus se baser exclusivement sur la couche de diff pour calculer les flux d’artif. D’après l’IGN cette couche n’a pas vocation à respecter les seuils d’artifs mais d’indiquer tout changement d’usage / occupation.
- d’indiquer sur le site spécifiquement pour chaque figure si celle-ci se base sur les seuils de qualification ou si ce sont des données brutes
- Modifier la carte comprendre l’artif qui affiche la couche d’artif et la couche de diff. Si une couche se base sur les seuils et l’autre non, on pourrait présenter des informations incohérentes.

**Comment by alexisig** [comment]
j'ai redécoupé en plusieurs US, je ferme celle ci
#389 
#394 
#392 
#391
