### ISSUE TITLE
Indiquer la différence entre données OCS GE 1.0 et 1.1

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#232]
[US Sur ClickUp](https://app.clickup.com/t/8693kjtcd)

 
Des utilisateurs ne comprennent pas toujours l'absence de données OCS GE alors qu'elles sont disponibles sur le site de l'IGN en version 1.0.
Indiquer la différence entre les deux versions et préciser que seules les données 1.1 peuvent être chargées sur MDA

**Comment by alexisig** [comment]
Les termes de l'IGN sont devenues :
- `ANCIENNE GÉNÉRATION` = 1.0
- `NOUVELLE GENERATION` = 1.1
