### ISSUE TITLE
Statistiques de diagnostics créés sur Metabase: ratio collectivités en révision de DU avec la compétence Urbanisme

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/sparte#236]
**Résumé**

En tant que Membre de l'équipe Mon Diag Artif' 
je souhaite Ouvrir Metabase
afin de Connaître la part de marché de la plateforme

**Critères d'acceptation**

(Que faut-il pour que cette tâche soit considérée comme terminée ?)
Gherkin (https://wefiit.com/rediger-en-gherkin/)

Étant donné que Dans la collection SUIVI MENSUEL de METABASE

Lorsque  Je sélectionne un intervalle de dates 
Alors dans la section "Nombre de portraits de l'Artificialisation des sols réalisés"
Ajouter plusieurs blocs : 

**Bloc 1** : "Diagnostics Créés par EPCI en révision de document d'urbanisme"
La liste des EPCI qui révisent leur document d'urbanisme s'obtient à partir de la règle 2
Style camembert comme similaires aux blocs "Diagnostics par région", "Diagnostics créés par département", "Diagnostics créés par Scots", "Diagnostics créés par EPCI" 

**Bloc 2** : "Diagnostics Créés par EPCI avec la compétence urbanisme"
La liste des EPCI qui ont la compétence urbanisme s'obtient à partir de la règle 3
Style camembert comme similaires aux blocs "Diagnostics par région", "Diagnostics créés par département", "Diagnostics créés par Scots", "Diagnostics créés par EPCI" 

**Bloc 3** : "Histogramme des diagnostics par EPCI" 
Représenter le ratio des diagnostics créés sur des EPCI par rapport à tous les EPCI
Représenter le ratio des diagnostics réalisés sur des EPCI qui ont la compétences urbanisme par rapport à tous les EPCI qui ont la compétence urbanisme
Représenter le ratio des diagnostics créés sur des EPCI en révision de document d'urbanisme par rapport à tous les EPCI qui révisent leur document d'urbanisme

**Bloc 4** : "Diagnostics Créés par Communes en révision de leur document d'urbanisme"
La liste des Communes qui révisent leur document d'urbanisme s'obtient à partir de la règle 4

**Bloc 5** : "Diagnostics Créés par Communes avec la compétence urbanisme"
La liste des EPCI qui ont la compétence urbanisme s'obtient à partir de la règle 5

**Bloc 6** : "Histogramme des diagnostics par Communes" 
Représenter le ratio des diagnostics créés sur des Communes par rapport à touts les Communes
Représenter le ratio des diagnostics réalisés sur des Communes qui ont la compétences urbanisme par rapport à tous les Communes qui ont la compétence urbanisme
Représenter le ratio des diagnostics sur des Communes en révision de document d'urbanisme par rapport à tous les EPCI qui révisent leur document d'urbanisme

**Règles de gestion** 

**Règle 1** - Filtrer les collectivités en révision de document d'urbanisme
Ouvrir le fichier  'ListeCommunes.csv' 
Filtre sur la colonne "DU_en_cours" 
Masquer les collectivités qui ne révisent pas leur document d'urbanisme en supprimant toutes celles qui ont "Aucun" dans la colonne "DU_en_cours" et celles pour lesquelles cette colonne est vide.

**Règle 2** - Les EPCI qui révisent leur document d'urbanisme
Appliquer Règle 1 
Obtenez la liste des EPCI qui révisent leur document d'urbanisme en masquant toutes les lignes dont la colonne 'SIREN EPCI' est vide.
Le nom de ces EPCI peut s'obtenir en faisant correspondre les numéros de SIREN obtenus à l'étape 2 avec ceux du fichier 'Liste_EPCI_SIREN.csv'

**Règle 3** - EPCI qui ont la compétence urbanisme
Ouvrir le fichier 'ListeCommunes.csv'
Récupérer le numéro de SIREN de tous les EPCI porteurs de document d'urbanisme (pas de filtre sur la colonne DU_en_cours)
Le nom de ces EPCI peut s'obtenir en faisant correspondre ces numéros de SIREN à ceux du fichier 'Liste_EPCI_SIREN.csv'

**Règle 4** - Les communes qui révisent leur document d'urbanisme
Appliquer Règle 1 
Masquer les EPCI de la liste obtenue en supprimant toutes les lignes qui ont une valeur dans la colonne SIREN EPCI

**Règle 5** - Les communes qui ont la compétence urbanisme
Ouvrir le fichier 'ListeCommunes.csv'
masquez les communes qui n'ont plus la compétence urbanisme en supprimant les lignes non vides pour la colonne 'SIREN EPCI' (pas de filtre sur la colonne DU_en_cours)

**Comment by NicolasM92** [comment]
[Uploading ListeCommunes.csv…]()

**Comment by inesdartiguenave** [comment]
@alexisig il y a l'API de Docurba qui correspond au référentiel de compétences recommandé par Sudocuh

**Comment by alexisig** [comment]
- [ ] Bloc 1 : Diagnostics Créés par EPCI en révision de document d'urbanisme
- [ ] Bloc 2 : Diagnostics Créés par EPCI avec la compétence urbanisme
- [ ] Bloc 3 : Histogramme des diagnostics par EPCI
- [x] Bloc 4 : [Diagnostics Créés par Communes en révision de leur document d'urbanisme](https://sparte-metabase.osc-secnum-fr1.scalingo.io/question/45-nombre-de-communes-qui-sont-en-revision-de-du-et-qui-ont-la-competence)
- [ ] Bloc 5 : Diagnostics Créés par Communes avec la compétence urbanisme
- [ ] Bloc 6 : Histogramme des diagnostics par Communes

**Comment by alexisig** [comment]
@JeremieSeguin est-ce que pour le bloc 6 ma compréhension est correcte si je reformule comme ça :
- 6.1 : part des communes ayant crée au moins un diagnostic comparée au nombre total des communes
- 6.2 : part des communes ayant la compétence urbanisme et ayant crée au moins un diagnostic comparée au nombre total de communes ayant la compétence urbanisme

Pour la 6.3 je suis pas sûr de comprendre, est-ce qu'il y a eu un mic-mac avec commune et EPCI dans la formulation ?

**Comment by inesdartiguenave** [comment]
@alexisig as-tu toujours des questions concernant les 6.1 et 6.2 ? 

L'intention est de faire le ratio entre communes + EPCI et situation (compétence urbanisme > doc d'urbanisme en cours d'élaboration)

### Pour les communes : 
- part des communes **ayant la compétence urbanisme** et ayant créé au moins un diagnostic comparée au nombre total de communes ayant la compétence urbanisme
- part des communes ayant la compétence urbanisme **ET un doc d'urbanisme en cours** et ayant crée au moins un diagnostic comparée au nombre total de communes ayant la compétence urbanisme

### Pour les EPCI : 
- part des EPCI **ayant la compétence urbanisme** et ayant créé au moins un diagnostic comparée au nombre total de communes ayant la compétence urbanisme
- part des EPCI ayant la compétence urbanisme **ET un doc d'urbanisme en cours** et ayant crée au moins un diagnostic comparée au nombre total de communes ayant la compétence urbanisme

### Total collectivités (EPCI + communes) : 
- part des EPCI + communes **ayant la compétence urbanisme** et ayant créé au moins un diagnostic comparée au nombre total de EPCI + communes ayant la compétence urbanisme
- part des EPCI + communes ayant la compétence urbanisme **ET un doc d'urbanisme en cours** et ayant crée au moins un diagnostic comparée au nombre total de EPCI + communes ayant la compétence urbanisme

**Comment by alexisig** [comment]
@inesdartiguenave ça change pas mal la demande initiale et l'effort devient beaucoup plus important (il y autant de requêtes dans le bloc 6 que dans le reste avec cette reformulation).
Est-ce ça te va si on sort le bloc 6 du sprint actuel et qu'on en fait une US séparée ?

**Comment by inesdartiguenave** [comment]
Ok pour un complément dans une prochaine itération => US #274

**Comment by JeremieSeguin** [comment]
> @JeremieSeguin est-ce que pour le bloc 6 ma compréhension est correcte si je reformule comme ça :
> 
> * 6.1 : part des communes ayant crée au moins un diagnostic comparée au nombre total des communes
> * 6.2 : part des communes ayant la compétence urbanisme et ayant crée au moins un diagnostic comparée au nombre total de communes ayant la compétence urbanisme
> 
> Pour la 6.3 je suis pas sûr de comprendre, est-ce qu'il y a eu un mic-mac avec commune et EPCI dans la formulation ?

C'est tout bon oui (modulo qu'on ne sache pas si ce sont les communes qui ont fait les diag). Ca pourra être une US à venir (à réaliser à partir des comptes utilisateurs / téléchargement de diag)

Il me semble que le 6.3 contient une coquille (EPCI au lieu de Communes)

Peut-être reformuler comme ça : Part des diagnostics sur des Communes en révision de document d'urbanisme par rapport à toutes les Communes qui révisent leur documents d'urbanismes [Comme bloc 3 mais pour les communes]

**Comment by JeremieSeguin** [comment]
Bloc 1 ; 2 et 3 semblent les mêmes datas mais sous une représentation différente. 
J'ai donc l'impression que les requêtes sont erronées. 

En vue des résultats, je déduis que mon US n'est pas claire. 
Je vais l'accompagner d'une maquette pour simplifier les choses.

**Comment by JeremieSeguin** [comment]
Le tableau de bord recherché sur METABASE est le suivant :

![Image](https://github.com/MTES-MCT/sparte/assets/117758546/f628fafe-6c29-4bce-8750-cc98bb65226d)
