### ISSUE TITLE
Séparer export conso et global

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/sparte#237]
Résumé

**4 exports à prévoir :**

un bouton : "exporter l'analyse de consommation" (document dans les commentaires)
un bouton : "exporter l'analyse complète" (bouton grisé s'il n'y a pas l'OCS GE)
un bouton : "exporter votre rapport triennal local" (grisé tant que pas disponible mais avec un message "bientôt disponible" au survol)
un bouton : "exporter au format Excel"

**Comment by alexisig** [comment]
Size en `L` si fait en même temps que #191

**Comment by inesdartiguenave** [comment]
@smdsgn tu trouveras dans ce doc les éléments à modifier / ajouter pour MAJ l'export de l'analyse complète en comparant avec le rapport local 

https://docs.google.com/document/d/1ZY7RxIj9ZyQEPhc47D0S12q25MZtC8r8/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

Excuse-moi de ne l'avoir réalisé + tôt

**Comment by smdsgn** [comment]
> @smdsgn tu trouveras dans ce doc les éléments à modifier / ajouter pour MAJ l'export de l'analyse complète en comparant avec le rapport local
> 
> https://docs.google.com/document/d/1ZY7RxIj9ZyQEPhc47D0S12q25MZtC8r8/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true
> 
> Excuse-moi de ne l'avoir réalisé + tôt

Merci, pas de souci.
