### ISSUE TITLE
Saas MonDiagArtif

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/sparte#244]
Pour chaque Saas dans la checklist
Ajouter Sofian et Alexis en administrateur
Si facturation gérée par Swann : basculer le facturation à la startup / à un autre membre de l'équipe si impossible de facturer au niveau de l'équipe

**Comment by alexisig** [comment]
@NicolasM92 est-ce que tu as [validé ton moyen de paiement](https://console.scaleway.com/organization/billing) sur Scaleway ? 

Si oui on peut fermer cette issue je pense

**Comment by NicolasM92** [comment]
Oui c'est validé. Par contre, as-tu reçu un feedback pour changer le nom de
l'entreprise pour les factures ?


*Nicolas Mouanga*Chargé de déploiement Senior
***@***.***
06 66 22 88 96

**Comment by alexisig** [comment]
Je viens de les relancer, je te tiens au courant 👍

**Comment by alexisig** [comment]
@NicolasM92 c'est fait 👍 
<img width="157" alt="image" src="https://github.com/MTES-MCT/sparte/assets/16051000/ee2f5f62-63c6-4db3-8893-b66964b1fbea">
