### ISSUE TITLE
Modifications liées au changement de North Star

### ISSUE THREAD

**Issue by smdsgn** [MTES-MCT/sparte#245]
Onglet Zonages d'urbanisme: 
- Masquer la section Taux de remplissage des zones AU et U  ✅
- Masquer la section Zones naturelles ayant été le plus artificialisées sur la période  ✅

Onglet Trajectoires : 
- Modifier titre de l'onglet: Trajectoires => Trajectoire 🙋 => Commentaire Inès : Je garderais trajectoires au pluriel pour l'instant. C'était une demande de la DGALN pour insister sur le fait qu'il n'y a pas encore 1 seule trajectoire établie tant que l'objectif n'est pas territorialisé et inscrit réglementairement dans les PLU(i)
=> Commentaire Jérémie : Comme la DGALN, Mon interlocuteur AURA n'a pas du tout perçu que l'objectif de réduction était un objectif non réglementaire mais plutôt un moyen de simuler le nombre d'hectares maximum disponibles en fonction d'un paramètre non réglementaire. 
Proposition : Appeler l'onglet simulateur / simulation ? 
- Masquer le bloc call to action Projection personnalisée  ✅
- Masquer la trajectoire du graphique et du tableau des données ✅ => Commentaire Inès : Sans cliquer sur "projection personnalisée" je n'ai pas l'impression qu'il y ait de graphique ou colonne dans le tableau de données. Ok pour retirer cette possibilité. Veiller à garder le graphique + tableau pour la trajectoire avec objectif de réduction.

Page liste diagnostics
- Supprimer les boutons "Piloter ma trajectoire" 🙋  
=> Commentaire Inès : Simuler ma trajectoire 
=> Jérémie :  Commentaire Jérémie : Simuler une trajectoire 

Page Accueil
- Hero section: Modifier base line "Estimez la trajectoire d'une collectivité selon sa consommation d'espaces des 10 dernières années et ses projets d'aménagement à  l'horizon 2031." 
=> Proposition Inès : Analysez la consommation d'espaces des 10 dernières années s(et estimez la potentielle trajectoire à horizon 2031."
=> Jérémie : Analysez la consommation d'espaces des 10 dernières années et simulez des trajectoires expérimentales pour l'horizon 2031."

Tuto section: Modifier 3ème bloc "Pilotez la consommation d'espaces grâce à l'outil de simulation de trajectoires" 
=> Proposition Inès : Inscrivez la collectivité dans la trajectoire de la loi Climat et Résilience avec le simulateur de trajectoire à horizon 2031 et bientôt le rapport local triennal"
=> Jérémie : Préservez les espaces Naturels, Agricoles et Forestiers à l'aide du simulateur de trajectoires. Ce simulateur n'est pas réglementaire et permet de prendre conscience des impacts de l'urbanisation à partir d'un simple paramètre utilisateur.

Page Tutoriel
- Modifier capture d'écran de la page d'accueil. ✅

Modification de l'ordre des onglets: ✅
Synthèse
Consommation
Trajectoires
Découvrir l'OCS GE
Artificialisation
Zonages d'urbanisme
Paramètres

Modifier phrase si utilisateur n'est pas connecté.
"Vous êtes actuellement en mode "anonyme". Si vous souhaitez retrouver votre diagnostic ou vos trajectoires lors de votre prochaine visite" (report_menu.html)

**Comment by inesdartiguenave** [comment]
Remarques recette : 

Page Accueil > Tuto section 

[Titre] Préservez les espaces Naturels, Agricoles et Forestiers à l'aide du simulateur de trajectoires.
[Sous-titre] Ce simulateur n'est pas réglementaire et permet de prendre conscience des impacts de l'urbanisation à partir d'un simple paramètre utilisateur.
