### ISSUE TITLE
La création de diagnostic de région retourne parfois un timeout

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#247]
En essayant de créer le diagnostic de la région occitanie:
![image](https://github.com/MTES-MCT/sparte/assets/16051000/6a16fc73-4686-4d19-bef4-7bc886349867)

**Comment by alexisig** [comment]
@JeremieSeguin est-ce que tu as vu cette page avant que ça crash ou est-ce que tu es resté bloqué sur page d'accueil ?


![Image](https://github.com/MTES-MCT/sparte/assets/16051000/5cd7f4bd-e79f-4954-b404-417804b3ff9a)

**Comment by JeremieSeguin** [comment]
Affirmatif, ça a cherché, cherché cherché .. puis écran bleu

**Comment by alexisig** [comment]
Je ferme pour l'instant, c'est sûrement lié au fait que la staging est très peu dimensionné et n'a pas tenu la charge. Si le bug apparait en prod on rouvrira.
