### ISSUE TITLE
Artificialisation selon zonages d'urbanisme_MAJ données GPU 

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#253]
Situation actuelle : dump GPU importé il y a quelques mois 

Situation souhaitée : données sur les zonages d'urbanisme récentes (zonages selon les dernières révisions des documents d'urbanisme)
- idéalement : MAJ en continu grâce à l'API GPU [(https://api.gouv.fr/les-api/api_carto_gpu)]
- à minima : nouvel import du dump

**Comment by alexisig** [comment]
@inesdartiguenave la mise à jour de cette donnée implique de recalculer les taux de "remplissage" pour tous les départements avec de l'OCS GE et pour chaque millésime disponible.

Pour faire une MAJ ponctuelle il faudrait :
- le faire avant / en même temps que le chargement des nouveaux départements #186 pour ne pas avoir à refaire les calculs sur ces départements
- refaire au même moment les calculs des départements déjà livré

A terme je pense qu'il faudrait :
- Automatiser le calcul du croisement GPU / OCS GE et mettre à jour _en continu_ notre BDD

---

Je suis en train de préparer les données des nouveaux départements OCS GE en ce moment. Si tu le souhaites, on peut déjà utiliser les nouveaux documents d'urbanisme pour cette livraison, mais ça implique de recalculer en même temps le croisement GPU / OCS GE des départements déjà livrés. A mon avis ce serait une bonne idée de le faire de cette manière, mais ça va retarder l'ensemble de la livraison, et nous éloigner de la prio sur la production des rapports trienaux.  Donc à mon avis, je pense qu'on aurait plus intêret à faire cette MAJ de donnée quand on aura le temps de l'automatiser entièrement.

Qu'est-ce que tu en penses ?

**Comment by inesdartiguenave** [comment]
@alexisig j'imagine que tu as choisi l'option la plus pertinente. Ok pour repousser la MAJ au travail sur l'automatisation.
