### ISSUE TITLE
Indiquer que le Rapport local sera bientôt disponible

### ISSUE THREAD

**Issue by smdsgn** [MTES-MCT/sparte#256]
Ajouter un bouton (non cliquable) "télécharger le rapport local" avec une étiquette "bientôt disponible"
Ajouter un onglet (non cliquable) "Rapport local" avec une étiquette "bientôt disponible"

**Comment by alexisig** [comment]
https://www.figma.com/file/8W2oa9Q0eKJKJrT0qJCHwA/SPARTE---UI-design?type=design&node-id=1715-11210&mode=design&t=prSjErFs44ne3QMh-0

**Comment by inesdartiguenave** [comment]
@smdsgn Retours recette sur onglet rapport local

- 2ème onglet point vers l'url 2021 au lieu de 2023 : https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000047866733 

- Sur le paragraphe ci-dessous : changer le texte en gras => période d'analyse; date de mise à disposition du dernier millésime sur mon diag artif 

Par exemple sur Mon Diag Artif le rapport local analysera la période **2011-2021**, en s'appuyant sur le dernier millésime publié par le Cerema. A date il s'agit du millésime du 1er janvier 2022 portant sur l'année 2021, celui du 1er janvier 2023 sera disponible **sur Mon Diagnostic Artificialisation** d'ici **juin** 2024.

- Dernier paragraphe : si possible éviter que l'avant dernière ligne commence par une parenthèse. Enlever l'espace avant ?

**Comment by inesdartiguenave** [comment]
@smdsgn 

La DGALN nous a fourni son texte pour la question 

### Quand doit être établi ce rapport et sur quelle période ?

**Garder :** Le premier rapport doit être réalisé 3 ans après l'entrée en vigueur de la loi, soit en 2024. 

**Remplacer cette partie :**
Le rapport local triennal doit être réalisé à minima tous les 3 ans, avec les données à disposition. Par exemple sur Mon Diag Artif le rapport local analysera la période 2011-2022, en s'appuyant sur le dernier millésime publié par le Cerema. A date il s'agit du millésime du 1er janvier 2022 portant sur l'année 2021, celui du 1er janvier 2023 sera disponible d'ici juillet 2024.

**Nouveau texte en remplacement*

A noter que c'est le rapport qui est triennal, et non la période à couvrir par le rapport :

- Il faut que le rapport soit produit a minima tous les 3 ans. Il est donc possible pour une collectivité qui le souhaite, de produire un rapport, par exemple tous les ans ou tous les 2 ans.

- La période à couvrir n'est pas précisée dans les textes. Étant donné que l’État met à disposition les données des fichiers fonciers depuis le 1er janvier 2011 (= début de la période de référence de la loi CR), il serait intéressant que le rapport présente la chronique des données du 1er janvier 2011 et jusqu'au dernier millésime disponible, pour apprécier la trajectoire du territoire concerné avec le recul nécessaire (les variations annuelles étant toujours à prendre avec prudence car pouvant refléter de simples biais méthodologiques dans les données sources). 

- Il n'est, bien évidemment, pas demandé d'inventer des données non encore disponibles : pour le rapport triennal à produire d'ici août 2024 il sera possible d'utiliser les fichiers fonciers au 1er janvier 2023, couvrant la consommation d'ENAF au titre de l'année 2022. 

### Que doit contenir ce rapport ?

**Sous les tableaux et le texte "Avant 2031, il n’est pas obligatoire de renseigner les indicateurs 2°, 3° et 4° tant que les documents d'urbanisme n'ont pas intégré cet objectif."

Note : La trame de rapport triennal proposée par Mon Diagnostic Artificialisation est une aide à la préparation du rapport pour les collectivités concernées ainsi que les services de l'Etat (pour les communes au RNU).

**Comment by inesdartiguenave** [comment]
@smdsgn @alexisig Quelques retours impliquant des modifs de texte sur l'onglet rapport local (les mêmes que sur issue export) 🙏

Retours DGALN

Sur le doc https://docs.google.com/document/d/173z6iYFGJEH125NpFZJ0_EbJeSKD8QMk/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**Objet du rapport local de suivi de l’artificialisation des sols**
MAJ du texte avec les ajouts et suppressions
