### ISSUE TITLE
Masquer les années 2009 et 2010

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#270]
### Situation actuelle 
diagnostic de conso d'espaces NAF commence dès 2009. 

### Situation souhaitée 
- diagnostic en libre accès / public commence dès 2011; en accord avec la période de référence. 
- si besoin d'inclure les années 2009-2010 changer les paramètres (bientôt avec l'accès compte)

### Résultat 
Alignement entre le diagnostic de consommation d'espaces et le rapport local (plateforme + export)

---- 

Relecture dev : mettre à jour la début par défaut à 2011 sur le diag en ligne et l'export

**Comment by inesdartiguenave** [comment]
lié à #191

**Comment by alexisig** [comment]
Est-ce qu'on peut préciser pourquoi ce changement est nécessaire ?

**Comment by inesdartiguenave** [comment]
Car les graphiques de l'export correspondent à ceux de la plateforme; et reprennent donc les années depuis 2009. Importance de commencer avec la période de référence; et les commentaires d'AL.W précisaient que ces données anciennes ne sont pas assez robustes. Cf. Google doc.
