### ISSUE TITLE
Créer un graphique de conso annuelle

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#273]
### Situation actuelle 

Le bilan de la conso année après année depuis 2011 est uniquement disponible sur la page trajectoires. Cependant l'indicateur est nécessaire pour l'export du rapport local. 

### Situation souhaitée

Page "Consommation" > dans la section "Consommation d'espace annuelle sur le territoire"

Proposition : changer le graphique actuel avec lignes en format histogramme pour la v1 

<img width="557" alt="Capture d’écran 2024-04-17 à 08 27 20" src="https://github.com/MTES-MCT/sparte/assets/84960477/9d8dfc7f-de1f-4a81-9ed9-d85b55af1f85">

Modifier rubrique "détails données et calcul" complémentaire : mettre en gras le total (en particulier au niveau EPCI)

### Questions pour la suite 
- est-ce que le passage à l'histogramme depuis 2011 est suffisant pour le rapport local ? Ou besoin d'un graphique + tableau complémentaire avec le total à la maille EPCI  ? 
- si autre graphique + tableau où le positionner sur la page conso ? et la carte consommation d'espaces des communes du territoire sur la période ?

**Comment by inesdartiguenave** [comment]
lié à https://github.com/MTES-MCT/sparte/issues/191

**Comment by alexisig** [comment]
@inesdartiguenave on a pas exactement compris ce qui est demandé. On en discute en atelier en tout à l'heure ?

**Comment by alexisig** [comment]
Similaire au graphique des déterminants de la conso (2ème graphique de la page conso)
