### ISSUE TITLE
Mettre en avant la disponibilité du rapport local sur la page d'accueil

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#279]
### Bloc 1 
[Reprendre le contenu du bloc 2 texte + image] **Analysez la consommation d'espaces NAF et l'artificialisation des sols via un diagnostic exportable.** Graphiques, tableaux de données et cartes interactives avec les calculs recommandés par le décret.

### Bloc 2
[Texte proposé par la DGALN + image "export files" sur Undraw] **Obtenez une trame pour votre rapport triennal local de suivi de l'artificialisation des sols**
Conformément à [l'article L. 2231-1 du code général des collectivités territoriales](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630)

![Image](https://github.com/MTES-MCT/sparte/assets/84960477/1c0d729e-caed-4782-859e-15be3e209917)

### Bloc 3
[MAJ du texte aligné avec dernière version page trajectoires + garder image] **Inscrivez la collectivité dans la trajectoire de la loi Climat et Résilience.** Simulateur d'objectif non-réglementaire de réduction de consommation d'espaces NAF d'ici 2031.

**Comment by JeremieSeguin** [comment]
Ok pour moi, top !

**Comment by smdsgn** [comment]
@inesdartiguenave Pour moi on sort du parcours utilisateur là. L'idée de ces blocs marqués des chiffres 1, 2 et 3 c'était d'indiquer qu'en 3 étapes tu pars d'une action et tu as une finalité. Avec ces modifications c'est plus le cas. On est d'accord que j'enlève les chiffres 1, 2 et 3 du coup ?

**Comment by inesdartiguenave** [comment]
@smdsgn nous avons plusieurs propositions avec les bizdev. 

Soit on fait un A/B test entre les 2 scénarii. Soit on prend le scénario A qui nous semble + clair. 

### Scénario A en retirant la notion de parcours et offrant un encart au rapport local 

Celui de l'US en remplaçant la sélection de territoire => Ok pour retirer les chiffres. 

### Scénario B en gardant la notion de parcours et les chiffres

Bloc 1 inchangé 

**Sélectionnez un territoire**
Nos diagnostics sont disponibles France entière à l'échelle de la commune, EPCI, SCoT, département ou région.


Bloc 2 -  - MAJ du texte

Analysez la consommation d'espaces NAF et obtenez une trame pour votre rapport triennal local de suivi de l'artificialisation des sols

Graphiques, tableaux de données, cartes interactives et rapport triennal conformément à [l'article L. 2231-1 du code général des collectivités territoriales](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630)

Bloc 3 - MAJ du texte

[MAJ du texte aligné avec dernière version page trajectoires + garder image] Inscrivez la collectivité dans la trajectoire de la loi Climat et Résilience. Simulateur d'objectif non-réglementaire de réduction de consommation d'espaces NAF d'ici 2031.

**Comment by JeremieSeguin** [comment]
> @smdsgn nous avons plusieurs propositions avec les bizdev.
> 
> Soit on fait un A/B test entre les 2 scénarii. Soit on prend le scénario A qui nous semble + clair.
> 
> ### Scénario A en retirant la notion de parcours et offrant un encart au rapport local
> Celui de l'US en remplaçant la sélection de territoire => Ok pour retirer les chiffres.
> 
> ### Scénario B en gardant la notion de parcours et les chiffres
> Bloc 1 inchangé
> 
> **Sélectionnez un territoire** Nos diagnostics sont disponibles France entière à l'échelle de la commune, EPCI, SCoT, département ou région.
> 
> Bloc 2 - - MAJ du texte
> 
> Analysez la consommation d'espaces NAF et obtenez une trame pour votre rapport triennal local de suivi de l'artificialisation des sols
> 
> Graphiques, tableaux de données, cartes interactives et rapport triennal conformément à [l'article L. 2231-1 du code général des collectivités territoriales](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630)
> 
> Bloc 3 - MAJ du texte
> 
> [MAJ du texte aligné avec dernière version page trajectoires + garder image] Inscrivez la collectivité dans la trajectoire de la loi Climat et Résilience. Simulateur d'objectif non-réglementaire de réduction de consommation d'espaces NAF d'ici 2031.

Ok pour Scénario A sans test A/B. 
Si test A/B : 
J'établirais 4 blocs dans le parcours (en ajoutant le bloc sur le rapport local triennal décrit dans l'US à l'étape 3 ou 4 suivant où l'on souhaite placer le bloc sur l'objectif réglementaire.
Mon avis mais à valider avec le métier, ils doivent s'assurer d'être dans les clous d'un objectif avant d'établir le rapport triennal (donc bloc 4 : rapport trienal)

**Comment by inesdartiguenave** [comment]
@smdsgn Pour conclure avec la remarque de Jérémie 

### Scénario A 

Scénario A en retirant la notion de parcours et offrant un encart au rapport local

Celui de l'US en remplaçant la sélection de territoire => Ok pour retirer les chiffres.

### Scénario B 

**Bloc 1 inchangé**
Sélectionnez un territoire 
Nos diagnostics sont disponibles France entière à l'échelle de la commune, EPCI, SCoT, département ou région.

**Bloc 2 - texte retirant l'export**

Analysez la consommation d'espaces NAF et l'artificialisation des sols
Graphiques, tableaux de données et cartes interactives avec les calculs recommandés par le décret.

**Bloc 3 - Texte proposé par la DGALN**
 + image "export files" sur Undraw (cf. 1er commentaire de cette US)

Obtenez une trame pour votre rapport triennal local de suivi de l'artificialisation des sols
Conformément à [l'article L. 2231-1 du code général des collectivités territoriales](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630)

**Bloc 4**
Inscrivez la collectivité dans la trajectoire de la loi Climat et Résilience. 
Simulateur d'objectif non-réglementaire de réduction de consommation d'espaces NAF d'ici 2031.
