### ISSUE TITLE
Page synthèse_ajouter un encart de l'onglet rapport local 

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#280]
Objectif : valoriser le rapport local dès la page d'atterrissage

Un encart précisant que le rapport local est disponible qui renvoie vers l'onglet dédié ? 
ou une proposition des différents exports avec les icones dont @smdsgn parlait ?

**Comment by alexisig** [comment]
@inesdartiguenave on se dit que le nouvel onglet, la homepage, le nouveau bouton de téléchargement et la landing page répondent déjà assez bien au besoin de mettre en avant la dispo du rapport local. Est-ce que tu penses que c'est tout de même nécessaire de faire un rappel dans la synthèse ?

**Comment by inesdartiguenave** [comment]
@alexisig Ok archivons cette US
