### ISSUE TITLE
Landing page rapport local

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#281]
### Le rapport local de suivi de l’artificialisation des sols

Le rapport local triennal détaillé à [l’article R. 2231-1 du code général des collectivités territoriales ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630) permet de mesurer et de communiquer régulièrement au sujet du rythme de l’artificialisation des sols, afin d’anticiper et de suivre la trajectoire et sa réduction. 

[Mise en forme selon 2 colonnes : dont 1 colonne sur la conso d'espaces pour 2021-2031 ? ]
Cette trajectoire est mesurée, pour la période 2021-2031, en consommation d’espaces NAF (naturels, agricoles et forestiers), définie comme « la création ou l'extension effective d'espaces urbanisés sur le territoire concerné » [(article 194, III, 5° de la loi Climat et résilience](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000043957223)). 

[Mise en forme selon 2 colonnes : dont 1 colonne sur l'artificialisation à partir de 2031 ? ]
A partir de 2031, cette trajectoire est également mesurée en artificialisation nette des sols, définie comme « le solde de l'artificialisation et de la renaturation des sols constatées sur un périmètre et sur une période donnés » ([article L.101-2-1 du code de l’urbanisme](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043967077/2023-09-04)).

### Préparer le rapport local avec Mon Diag Artif 

L'équipe travaille à la production automatique du rapport local. 

« 1° La consommation des espaces naturels, agricoles et forestiers, exprimée en nombre d'hectares, le cas échéant en la différenciant entre ces types d'espaces, et en pourcentage au regard de la superficie du territoire couvert ; 

Indicateur obligatoire. Disponible sur Mon Diag Artif d'ici juin 2024, France entière  

2° Le solde entre les surfaces artificialisées et les surfaces désartificialisées, telles que définies dans la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid) ;

Indicateur non obligatoire. Bientôt disponible sur Mon Diag Artif, pour les territoires avec l'OCS GE.

3° Les surfaces dont les sols ont été rendus imperméables, au sens des 1° et 2° de la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid) ;

Indicateur non obligatoire. Bientôt disponible sur Mon Diag Artif, pour les territoires avec l'OCS GE.

4° L'évaluation du respect des objectifs de réduction de la consommation d'espaces naturels, agricoles et forestiers et de lutte contre l'artificialisation des sols fixés dans les documents de planification et d'urbanisme. Les documents de planification sont ceux énumérés au [III de l'article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid). 

Indicateur non obligatoire. Non prévu dans Mon Diag Artif. 

### Call to action numéro 1 

Inscrivez-vous à notre lettre d'infos pour être notifié de la mise en ligne du rapport local 
[Votre adresse électronique : ex nom@domaine.fr] 

_NOTE : prochain call to action recherche de territoire ⇒ accès direct rapport local_

**Comment by JeremieSeguin** [comment]
###  Forme et structure de la page

Proposition : Je garderais la structure de notre home page -> 

1. Call To Action Numéro 1 dans un dégradé violet à bleu avec le champs @ à la place du champ recherche actuel. 
2. Préparer le rapport local avec Mon Diag Artif (mise en plage comme dans l'onglet Rapport local)
3.  Les aspects réglementaires, dans un bloc vert 

### Verbalisation

**Le rapport local de suivi de l’artificialisation des sols**

"Le rapport local triennal détaillé à [l’article R. 2231-1 du code général des collectivités territoriales ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630)permet de mesurer et de communiquer régulièrement **au sujet du rythme de l’artificialisation des sols**, afin d’anticiper et de suivre la trajectoire et sa réduction."

Question : la partie en gras "au sujet du rythme de l'artificialisation des sols", c'est dans les textes écrits ? comme beaucoup des collectivités ne pourront fournir des informations que sur la conso, je me demande si on ne pourrait pas le rajouter ? 


**Préparer le rapport local avec Mon Diag Artif**
L'équipe travaille à la production automatique du rapport local. 

Proposition 1 : L'équipe travaille à la production automatique d'une trame du rapport local. 
Proposition 2 : L'équipe travaille à la production automatique d'une trame pré remplie du rapport local.

**Comment by inesdartiguenave** [comment]
Merci @JeremieSeguin pour ta proposition. Pour le texte c'est effectivement la version officielle. La partie préparer le rapport explicite que le seul indicateur obligatoire est la conso d'espaces. 

Si je reprends : 

### Call to action 

Call To Action Numéro 1 dans un dégradé violet à bleu avec le champs @ à la place du champ recherche actuel.

Inscrivez-vous à notre lettre d'infos pour être notifié de la mise en ligne du rapport local
[Votre adresse électronique : ex [nom@domaine.fr](mailto:nom@domaine.fr)]

## Préparer le rapport local avec Mon Diag Artif

L'équipe travaille **avec la DGALN à la production automatique d'une trame pré remplie du rapport local.**

« 1° La consommation des espaces naturels, agricoles et forestiers, exprimée en nombre d'hectares, le cas échéant en la différenciant entre ces types d'espaces, et en pourcentage au regard de la superficie du territoire couvert ;

Indicateur obligatoire. Disponible sur Mon Diag Artif d'ici juin 2024, France entière

2° Le solde entre les surfaces artificialisées et les surfaces désartificialisées, telles que définies dans la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid) ;

Indicateur non obligatoire. Bientôt disponible sur Mon Diag Artif, pour les territoires avec l'OCS GE.

3° Les surfaces dont les sols ont été rendus imperméables, au sens des 1° et 2° de la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid) ;

Indicateur non obligatoire. Bientôt disponible sur Mon Diag Artif, pour les territoires avec l'OCS GE.

4° L'évaluation du respect des objectifs de réduction de la consommation d'espaces naturels, agricoles et forestiers et de lutte contre l'artificialisation des sols fixés dans les documents de planification et d'urbanisme. Les documents de planification sont ceux énumérés au [III de l'article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid).

Indicateur non obligatoire. Non prévu dans Mon Diag Artif.

### [réglementaire] Le rapport local de suivi de l’artificialisation des sols 

Le rapport local triennal détaillé à [l’article R. 2231-1 du code général des collectivités territoriales ](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000048470630)permet de mesurer et de communiquer régulièrement au sujet du rythme de l’artificialisation des sols, afin d’anticiper et de suivre la trajectoire et sa réduction.

[Mise en forme selon 2 colonnes : dont 1 colonne sur la conso d'espaces pour 2021-2031 ? ]
Cette trajectoire est mesurée, pour la période 2021-2031, en consommation d’espaces NAF (naturels, agricoles et forestiers), définie comme « la création ou l'extension effective d'espaces urbanisés sur le territoire concerné » [(article 194, III, 5° de la loi Climat et résilience](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000043957223)).

[Mise en forme selon 2 colonnes : dont 1 colonne sur l'artificialisation à partir de 2031 ? ]
A partir de 2031, cette trajectoire est également mesurée en artificialisation nette des sols, définie comme « le solde de l'artificialisation et de la renaturation des sols constatées sur un périmètre et sur une période donnés » ([article L.101-2-1 du code de l’urbanisme](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043967077/2023-09-04)).

### Rappel du call to action 

Call To Action Numéro 1 dans un dégradé violet à bleu avec le champs @ à la place du champ recherche actuel.

Inscrivez-vous à notre lettre d'infos pour être notifié de la mise en ligne du rapport local
[Votre adresse électronique : ex [nom@domaine.fr](mailto:nom@domaine.fr)]

**Comment by NicolasM92** [comment]
En phase avec la proposition de Jérém, en terme de mots-clés, le terme "artificialisation", qui correspond à la requête la plus tapée, est bien représenté donc on est bon!

**Comment by inesdartiguenave** [comment]
Proposition de la DGALN : une URL du style https://mondiagnosticartificialisation.beta.gouv.fr/rapport_triennal

**Comment by inesdartiguenave** [comment]
@smdsgn Voici les retours à prendre en compte pour la page d'accueil. Appliquons les à l'onglet rapport local pour être cohérents. 

### Recette DGALN 

_1/  **pour distinguer les indicateurs obligatoires et optionnels** : 
- remplacer le pictogramme "croix sur fond rouge" (qui donne l'impression à tort qu'il est interdit d'utiliser cet indicateur) 
- par un pictogramme "V" sur fond gris (qui exprime mieux, que ce n'est qu'optionnel)._

=> Reformulation Inès : pictogramme de check en gris ☑️ 

_**2/ compléter ainsi la rédaction de la partie "cadre réglementaire"** 

"Le rapport local triennal détaillé à l’article R. 2231-1 du code général des collectivités territoriales permet de mesurer et de communiquer régulièrement au sujet du rythme de l’artificialisation des sols, afin d’anticiper et de suivre la trajectoire et sa réduction à l'échelle d'un document de planification ou d'urbanisme.

Cette trajectoire est mesurée, pour la période 2021-2031, en consommation d’espaces NAF (naturels, agricoles et forestiers), définie comme « la création ou l'extension effective d'espaces urbanisés sur le territoire concerné » (article 194, III, 5° de la loi Climat et résilience). Le bilan de consommation d'espaces NAF s'effectue à l'échelle d'un document de planification ou d'urbanisme.

A partir de 2031, cette trajectoire est également mesurée en artificialisation nette des sols, définie comme « le solde de l'artificialisation et de la renaturation des sols constatées sur un périmètre et sur une période donnés » (article L.101-2-1 du code de l’urbanisme). L'artificialisation nette des sols se calcule à l'échelle d'un document de planification ou d'urbanisme."_

=> Reformulation Inès : Annule et remplace le texte précédent. Garder le lien vers les articles de loi.
