### ISSUE TITLE
Bug_Page conso_surface_données manquantes

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#294]
Page conso > section surface > conso d’espaces par ménage > graphique + données >  il manque les données d'1 année 

**Année 2013 pour commune Gresy-sur-isère** 

<img width="1138" alt="Capture d’écran 2024-04-23 à 19 27 36" src="https://github.com/MTES-MCT/sparte/assets/84960477/a1e743f3-a008-4ce1-901b-9fbb59a6a69e">

**année 2015 pour commune du département Ambillou**
<img width="1269" alt="Capture d’écran 2024-04-25 à 10 00 06" src="https://github.com/MTES-MCT/sparte/assets/84960477/5b0a2b9e-5760-4c3e-b5e1-0f7ef6272680">

**Comment by alexisig** [comment]
Je ferme comme les graphiques vont être refait
