### ISSUE TITLE
Découvrir l'OCS GE -> Tableau de données (couverture et usage) -> Remplacer les "-" par 0

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#295]
**Quelle diff entre l’évolution à 0 ou avec un tiret ?** 

<img width="1183" alt="Capture d’écran 2024-04-24 à 13 01 06" src="https://github.com/MTES-MCT/sparte/assets/84960477/074cb0cb-852b-40c5-b9b8-b87a5bed760b">

**Comment by alexisig** [comment]
La règle en place affiche un `-` quand la valeur de la différence est égale à 0 :

```jinja
{% if item.surface_diff == 0 %}-
{% else %}
    {% if item.surface_diff > 0 %}+{% endif %}
    {{ item.surface_diff|floatformat:1 }}
{% endif %}
```

On remplace et on affiche simplement 0 ?

**Comment by inesdartiguenave** [comment]
@alexisig Oui parfait ça permet d'uniformiser
