### ISSUE TITLE
Bug_page artificialisation 

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#298]
**Page artif > grandes familles d’usage + couverture : pb de total**
ex commune Ambillou 

Ex : total à 277 ha au lieu de 27 

<img width="1251" alt="Capture d’écran 2024-04-24 à 14 23 03" src="https://github.com/MTES-MCT/sparte/assets/84960477/85825915-3441-41c0-8379-9f4d77b42cc5">

**Comment by alexisig** [comment]
Il me semble que le total est correct : la colonne "Artificialisé" représente le total d'artif du territoire, et la colonne "Artificialisation" la différence d'artif entre le premier millésime et le dernier millésime d'ocs ge dispo sur le territoire.
Par contre les lignes montrent toutes 0 et ça c'est bien un bug. Le bug fix est en cours : #299
