### ISSUE TITLE
Modifier le champ "Organisme" des formulaires de création de compte et téléchargements 

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#312]
### Nouvelle liste
- Agence d'urbanisme
- Bureau d'études
- Commune
- EPCI
- SCoT
- DDT
- DDTM (nouveau)
- DEAL (nouveau)
- DREAL
- DRIEAT (nouveau)
- Association
- Particulier
- Autre

### Suppression de
- Aménageur -> Ventilé dans "Autre"
- EPF -> Ventilé dans "Autre"
- GIP -> Ventilé dans "Autre"
- Département -> Ventilé dans DDT
- Region -> Ventilé dans DREAL

----

### Technique

- [ ] Remplacer les groupes hard-codé par un `TextChoices` (similaire à `ORGANISMS`)
- [ ] Mettre à jour la commande `get_group` en attributant chaque entité à un groupe.
    - Agence d'urbanisme -> Bureaux d'études
    - Bureau d'études -> Bureaux d'études
    - Commune -> Collectivités
    - EPCI -> Collectivités
    - SCoT -> Collectivités
    - DDT -> Services de l'Etat
    - DDTM (nouveau) -> Services de l'Etat
    - DEAL (nouveau) -> Services de l'Etat
    - DREAL -> Services de l'Etat
    - DRIEAT (nouveau) -> Services de l'Etat
    - Association -> Grand public
    - Particulier  -> Grand public

**Comment by inesdartiguenave** [comment]
@JeremieSeguin 

Itération : 

-     Agence d'urbanisme ou Bureau d'études
-     Commune
-     EPCI
-     SCoT
-     **DDT(M)/DEAL 
-     DREAL** 
-     Autre

Côté services déconcentrés de l'Etat : 
- échelle départementale : DDT(M) / DEAL (pour outre mer) (et DRIEAT mais c'est pour l'ile de France)
- échelle régionale : DREAL 

https://www.ecologie.gouv.fr/services-deconcentres-du-ministere

D'accord avec qui ont été retirés. 

Good pour toi ?

**Comment by JeremieSeguin** [comment]
Yes, parfait ! 
Merci

**Comment by alexisig** [comment]
Recommandation : pour ne pas perdre de données on pourrait garder distinct chaque type d'administration séparément.
La liste ressemblerait à :

- Agence d'urbanisme
- Bureau d'études
- Commune
- EPCI
- SCoT
- DDT
- DDTM
- DEAL
- DREAL
- DRIEAT

Est-ce que vous confirmez que vous voulez qu'on supprime les types suivants : 
- Aménageur
- Association
- EPF
- GIP
- Particulier

Je trouve les champs "association" et "particulier" intéressants personnellement, on a d'ailleurs pas mal de demandes qui viennent de ces types d'utilisateurs. Par exemple pour ce mois : 
<img width="1457" alt="image" src="https://github.com/MTES-MCT/sparte/assets/16051000/9a115b97-88b1-4655-9636-5d3c1d4891a8">
- 152 associations
- 218 particuliers

**Comment by JeremieSeguin** [comment]
Ok pour garder association et particulier

**Comment by inesdartiguenave** [comment]
Donc on supprime uniquement : 
- Aménageur
- EPF
- GIP

**Comment by alexisig** [comment]
@inesdartiguenave j'ai mis à jour le premier message en résumant toutes les infos de l'issue. Est-ce que ça te convient ?
