### ISSUE TITLE
Mise à jour d'attributs BREVO lors de la création ou téléchargement de diagnostics 

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#313]
Lorsque c'est possible (c'est à dire selon si on est dans le cadre d'une création de diag par un utilisateur connecté ou un téléchargement de diag par un utilisateur connecté ou non), renseigner les attributs BREVO suivants : 

DATE_CREATION_COMPTE _(format date)_ = date de création du compte utilisateur

FONCTION _(format texte)_ = fonction (métier)

A_TELECHARGE_BILAN _(format texte)_ = mettre OUI si Export Word (pas rapport triennal) 

A_TELECHARGE_RAPPORT_TRIENNAL _(format booléen)_ = A oui si téléchargé au moins un rapport triennal 

LAST_DPT_DIAGNOSTIC _(format nombre)_ = Numéro du département du territoire concerné par la MAJ de l'attribut

LAST_DATE_DIAG_CREATED _(format date)_ = Dernier Diag Créé 

LAST_DATE_DL_DIAG _(format date)_ = dernier Diag Téléchargé (rapport triennal ou conso)

DATE_DERNIER_RAPPORT_LOCAL_TELECHARGE = date du dernier rapport téléchargé

VERSION_DERNIER_RAPPORT_TELECHARGE = version du dernier rapport téléchargé

ORGANISME _(format texte)_ = organisme  

NOM_TERRITOIRE _(format texte)_ = Nom du dernier territoire diagnostiqué 

DU_EN_COURS _(format texte)_ = renseigner OUI si NOM_TERRITOIRE est en cours de révision ou élaboration du DU 

A_COMPETENCE_URBA _(format texte)_ = renseigner OUI si NOM_TERRITOIRE a la compétence URBA  (pas besoin d'avoir un compte)

NB_DIAG_CREES _(format nombre)_ = nbre de diag créés (besoin d'avoir un compte et être connecté pour implémenter ce nombre)

NB_DIAG_TELECHARGES  _(format nombre)_ = nombre diag téléchargés (pas besoin d'avoir un compte pour implémenter ce nombre)

ℹ️ : Une US dans clickup a déjà été livrée en PROD : https://app.clickup.com/t/860r5qq2z

**Comment by alexisig** [comment]
@JeremieSeguin 
Quelques questions en vrac : 
- FONCTION : si l'utilisateur est connecté, a renseigné une fonction en créant son compte, et qu'il remplit le champs fonction du formulaire de téléchargement, on a deux infos différentes. Laquelle tu penses est la plus pertinente ? Personnellement je garderais celle du compte et ignorerais l'autre, mais comme tu préfères 
- LAST_DPT_DIAGNOSTIC: le code actuel fait une concatenation de ce genre : "35,56" pour les diags sur les régions et les EPCI étalé sur plusieurs départements. Est-ce que ça te convient ? On pourrait aussi remplacer le champs par qqch de plus exhaustif, par exemple avec deux champs, un qui dit le type de territoire (commune, epci etc.) et un autre qui donne l'identifiant
- VERSION_DERNIER_RAPPORT_TELECHARGE: pour ce champs est-ce que la version officielle (celle du changelog) te convient ?
- DU_EN_COURS : le territoire peut être en révision ou non au moment du téléchargement du diag, mais le champs ne restera pas fiable avec le temps. Est-ce que ça te va si ma compréhension de ce champs est "DU en cours au moment du dernier téléchargement (tout type de rapport)" ?
- A_COMPETENCE_URBA: comme pour DU_EN_COURS

**Comment by alexisig** [comment]
> LAST_DPT_DIAGNOSTIC : ta solution avec deux champs me va bien mieux en effet.. peut-être garder le numéro du DPT pour cet attribut. Je viens de créer un nouvel attribut "DERNIER_TERRITOIRE_DIAG" (format texte) pour le nom du territoire

J'ai pas compris ce qu'on faisait du coup 

> VERSION_DERNIER_RAPPORT_TELECHARGE : Dans l'idée pourquoi pas, oui ! A quoi ressemble le changelog ? (l'idée de cet attribut est d'informer les personnes de la mise à jour du rapport comme par exemple la mise à dispo des zones artificialisées ou imperméabilisées)
Le changelog avec les différentes version : https://github.com/MTES-MCT/sparte/blob/master/CHANGELOG.md

> NBRE_DIAG_TELECHARGE (format nombre) = nombre de diag téléchargés tout confondu (analyse complete + rapport local) serait-ce ok pour toi ?
yes pas de soucis, tu l'avais déjà mis dans l'US :)

**Comment by JeremieSeguin** [comment]
> > LAST_DPT_DIAGNOSTIC : ta solution avec deux champs me va bien mieux en effet.. peut-être garder le numéro du DPT pour cet attribut. Je viens de créer un nouvel attribut "DERNIER_TERRITOIRE_DIAG" (format texte) pour le nom du territoire
> 
> J'ai pas compris ce qu'on faisait du coup


Tu proposais remplacer le champs par qqch de plus exhaustif, par exemple avec deux champs, un qui dit le type de territoire (commune, epci etc.) et un autre qui donne l'identifiant du coup j'ai créé un nouveau champs =) ?

**Comment by alexisig** [comment]
@JeremieSeguin 
Donc si j'ai bien compris :
Type de territoire = DERNIER_TERRITOIRE_DIAG
Id du territoire = LAST_DPT_DIAGNOSTIC

Si c'est bien ça, à mon avis les noms sont pas du tout explicites et on risque de plus rien y comprendre dans 6 mois 😅

Est-ce qu'on peut faire qqch du genre ?
Type de territoire = DERNIER_DIAG_TYPE_TERRITOIRE (REGION, DEPART, SCOT, EPCI, COMM)
Id du territoire = DERNIER_DIAG_ID_TERRITOIRE (code insee, siren etc.)
