### ISSUE TITLE
Documenter les départements avec OCS GE 

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#317]
### Situation actuelle 

Difficile de savoir quels sont les départements : 
- avec OCS GE sur Mon Diag Artif

### Situation souhaitée

Carte de France avec l'état de l'OCS GE selon les départements

**Titre** 

Départements couverts par l'OCS GE sur Mon Diag Artif 

**Localisation**

- sur notre home page

**Comment by JeremieSeguin** [comment]
Bonne idée cette US ! 

Je verrais bien la carte : 

- sur notre home page (pourquoi pas en scindant les trois blocs des producteurs de données en parties et rattacher la carte à la partie IGN), 

- dans l'onglet Artificialisation des territoires non encore couverts avec un formulaire d'inscription à la lettre d'infos pour être notifié de la disponibilité des données
