### ISSUE TITLE
Stats Metabase rapport local

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#322]

**Comment by JeremieSeguin** [comment]
Description : 

L'idée est de comprendre l'usage de la plateforme sur les territoires dont le rapport local a une forte utilité : 

- Les EPCI ; 
- Les communes qui ont la compétence urbanisme 
- Les communes au RNU 

Pour chaque type de territoire, renseigner : 
- le nombre de rapports locaux téléchargés 
- le % de rapports téléchargé par rapport au nombre total de territoire concernés (exemple : 14% de tous les EPCI ont vu au moins rapport local téléchargé)
![Maquette Stats rapport local](https://github.com/MTES-MCT/sparte/assets/117758546/1963c3e1-1d39-4cfc-bcbb-5c307559781d)

- le nombre de rapport moyen téléchargé par type de territoire (par exemple, sur tous les EPCI c'est en moyenne 2 rapports qui sont téléchargés)

**Comment by inesdartiguenave** [comment]
@JeremieSeguin 

A/ en relisant cette issue : est-ce qu'on pourra savoir le nb de rapports locaux créés ? Seulement téléchargés s'ils ne sont pas créés de compté. 

B/ la DGALN souhaitait savoir si le nb de rapports locaux équivaut au nb de territoires ayant téléchargé un rapport. Serait ce possible d'avoir l'info du nb de rapports locaux total; dont x territoires (ayant eu 1+ rapports local) ?

**Comment by inesdartiguenave** [comment]
@alexisig pour le référentiel des collectivités qui ont la compétence urbanisme : 

- source officielle; bien structurée; mais pas mise à jour régulièrement (csv) : Sudocuh 
- future source; en cours de documentation; MAJ en continu (API) : Docurba [](https://dev.docurba.beta.gouv.fr/dev/api)

**Comment by inesdartiguenave** [comment]
@alexisig quel référentiel de compétences prends-tu ?

- Banatic
- Sudocuh 

Si Sudocuh; le référentiel de compétence urbanisme est présent dans l'API Docurba [(https://dev.docurba.beta.gouv.fr/dev/api)]

**Comment by alexisig** [comment]
@inesdartiguenave On utilise Sudocuh en se basant sur le fichier csv mentionné sur cette US : #236 

Quelques questions en vracs : 
- La donnée est-elle plus complète ?
- Si oui : de quelles différences parle-t-on ? 
- Quelle est la source de donnée de l'API ?

L'utilisation d'une API plutôt que d'un fichier plat type csv complexifie notre travail de statistiques. Si la donnée existe à l'échelle communale, pour mettre à jour notre base de donnée il faudrait faire 30K requêtes à l'API, alors qu'importer le csv de sudocuh prend environ 1 seconde.

Je serais plutôt d'avis de garder le système existant avec Sudocuh importé depuis le CSV présent sur data gouv,  et le mettre à jour régulièrement (ça prendra toujours 1 seconde).

**Comment by HermanceGauth** [comment]
Bonjour @alexisig je me permets de commenter. 

Sur la compétence il existe donc deux référentiels qui évoluent en parallèle, Sudocuh et Banatic, qui sont parfois d'accord et parfois non. Quand ils ne le sont pas, l'erreur peut venir soit de Banatic (source préfecture) soit de Sudocuh (source DDT), il n'y a pas vraiment de règle générale. 

On pense que le référentiel de Sudocuh est plus proche de la réalité car rempli par des personnes dont le cœur de métier est la planif', ce qui n'est pas forcément le cas en préfecture. Mais on a déjà vu un cas où Banatic avait raison et Sudocuh tord. 

Avec la reprise des données par Docurba, notre but est de tendre vers un seul et même référentiel, celui de Banatic corrigé par les retours utilisateurs, mais ce n'est pas encore le cas aujourd'hui.

**Comment by alexisig** [comment]
Top, merci pour les infos @HermanceGauth.

Est-ce qu'à terme vous prévoyez de contribuer vos correctifs à Banatic / Sudocuh ?

**Comment by alexisig** [comment]
> Pas sûre de bien comprendre la question mais notre souhait serait de transmettre le correctif à la DGCL qui gère Banatic pour que leur référentiel soit mis à jour. C'est là la difficulté car il faut mettre en place ce process avec eux et ce n'est pas le cas encore aujourd'hui.

C'était ma question ! Merci pour les infos.
