### ISSUE TITLE
Rapport v2 avec l'artificialisation des sols

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#335]
**Situation actuelle** 

Rapport local v1 avec l'indicateur 1 sur la consommation d'espaces. D'ici mi mai avec le millésime 2023. 
https://docs.google.com/document/d/173z6iYFGJEH125NpFZJ0_EbJeSKD8QMk/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**Situation souhaitée** 

Rapport local v2 avec les indicateurs 2 + 3 sur l'artificialisation des sols. 
Note : le contenu déjà en prod sur le cadre réglementaire + indicateur 1 est plus à jour sur la v1 que dans ce doc. Se référer au doc suivant uniquement pour les indicateurs 2 + 3 + 3 sur l'artificialisation des sols. 

https://docs.google.com/document/d/1enXF3iqHOtyU1FMDL7jVPT_IlHkyFtyc/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

Eléments relatifs à l'indicateur 3 à changer par rapport à l'export complet : 
-  [x] MAJ trame + texte concernant l'artificialisation
- [x] Ajouter tableau de données « évolution de l’artificialisation » : ArtifWaterfallChartExport]
-  [x] Déplacer indicateur « répartition de l’artificialisation nette »  (graphique + tableau de données) : NetArtifComparaisonChartExport

**Comment by inesdartiguenave** [comment]
@smdsgn Voici l'issue sur la v2 du rapport avec l'artificialisation des sols

**Comment by alexisig** [comment]
La partie 3 parle d'imperméabilisation et c'est une donnée qu'on a pas encore. Il y a une fiche officielle pour le calculer :
https://artificialisation.developpement-durable.gouv.fr/sites/artificialisation/files/inline-files/Fiche_Indicateur_Impermeabilisation.pdf

Recommandation : on pourrait séparer l'US en deux parties, celle-ci pour l'artif, et une autre pour l'imperméabilisation.

--- 

Question pour l'artif : est-ce qu'on priorise la mise en place de la nouvelle méthode calcul de l'artif (#228) pour mon retour ? (à mon avis c'est pas bloquant de faire le rapport local avec l'ancienne méthode dans un premier temps, la différence est minime, mais à terme ça peut être pas mal de suivre toutes les recos officielles)

**Comment by inesdartiguenave** [comment]
@alexisig bien vu. J'ai créé l'issue #342 Rapport v3 avec l'imperméabilisation des sols

**Comment by smdsgn** [comment]
@inesdartiguenave Pas trop pertinent d'ajouter le tableau de données du graphique ArtifWaterfallChartExport je pense car les mêmes chiffres se retrouvent dans le texte au dessus.

![Image](https://github.com/MTES-MCT/sparte/assets/16525551/60d35054-8d25-453f-b9d3-55276c057450)

**Comment by inesdartiguenave** [comment]
@smdsgn comme évoqué en commentaire sur doc, dans ce cas conservons le graphique et retirons le texte. Cela permet de garder la cohérence entre graphique + tableau de données.
