### ISSUE TITLE
Bugs détails zonage d'urbanisme

### ISSUE THREAD

**Issue by smdsgn** [MTES-MCT/sparte#343]
Le graphique de la section "Artificialisation nette" ne s'affiche plus
Corriger la typo sur le titre de la section: Artificialisation net => Artificialisation nette
Le titre de la section Artificialisation nette disparait quand le graphique apparait

![Image](https://github.com/MTES-MCT/sparte/assets/16525551/b4f42e17-929c-4432-80b4-a798bb83c010)

**Comment by inesdartiguenave** [comment]
@smdsgn c'est artificialisation **nette** je pense

**Comment by smdsgn** [comment]
> @smdsgn c'est artificialisation **nette** je pense

Oui c'est pour ça que j'ai mis: Corriger la typo sur le titre de la section: Artificialisation net => Artificialisation nette
