### ISSUE TITLE
Bug données manquantes détail zonage d'urbanisme

### ISSUE THREAD

**Issue by smdsgn** [MTES-MCT/sparte#346]
Il manque le millésime ainsi que la zone artificialisée dans les tableau de données du détail des zonages d'urbanisme.

Tableau de données "Grandes familles de couverture des sols des surfaces artificialisées"

![Image](https://github.com/MTES-MCT/sparte/assets/16525551/4fa9b14d-570a-441b-ba2c-3543588f716e)

Tableau de donnée "Grandes familles d'usages du sol des surfaces artificialisées"

![Image](https://github.com/MTES-MCT/sparte/assets/16525551/73760b64-96a8-4a6a-aadf-767af5081425)

**Comment by alexisig** [comment]
A régler en même temps : (millésime min : , millésime max : ).
