### ISSUE TITLE
Téléchargement package des rapports locals des communes au RNU d'un département

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#349]
### Situation actuelle

En tant que département je souhaite télécharger les rapports locaux des communes au RNU de mon périmètre, or je dois à chaque fois créer un diag + soumettre le formulaire.

### Situation souhaitée

En tant que département > quand je clique sur rapport local... 

- **version fonctionnelle** : je souhaite sélectionner les communes pour lesquelles télécharger un package de rapports locaux

- **version optimisée pour + tard** : je souhaite valider / modifier la liste des communes au RNU sur la base d'une présélection (avec le référentiel de compétences)

**Conditions** 
Croisement avec les données Sudocuh sur les documents d'urbanisme en vigueur

**Comment by Phil-Loriot** [comment]
On peut aussi se dire qu'on préproduit l'ensemble des rapports des communes au RNU (plus de 9000) et de les zipper par département pour permettre un téléchargement global...

**Comment by alexisig** [comment]
@Phil-Loriot oui on peut faire ça en one-off pour l'échéance du mois d'aout.
quand est-ce que tu penses qu'on devrait faire ces packages ? A mon avis plus on attend mieux c'est car les rapports seront plus complets / plus quali avec l'intégration des retours qu'on aura eu entre temps

**Comment by inesdartiguenave** [comment]
@alexisig @smdsgn nous ré-activons l'issue avec Philippe suite à votre discussion en affinage. 

Pré-calcul des diags uniquement pour les communes au RNU (pour l'instant) afin de fournir un .zip par département

**Comment by inesdartiguenave** [comment]
@alexisig @smdsgn la DGALN nous a communiqué que le téléchargement pour les DDT est + prioritaire que l'intégration de l'imperméabilisation, optionnelle pour l'instant. Nous en discuterons lors de la priorisation lundi en équipe.

**Comment by alexisig** [comment]
@inesdartiguenave @Phil-Loriot 
Pour pouvoir les faire on aurait besoin de votre go sur ces points : 
- Augmenter considérablement la taille du serveur pendant l'opération. On pourra revenir sur la taille actuelle ensuite. 
- Utiliser le fond de carte de l'OpenStreetMap au lieu de l'orthophoto

**Comment by Phil-Loriot** [comment]
bien sur oui

**Comment by alexisig** [comment]
@Phil-Loriot @inesdartiguenave 
Je viens de finir les tests sur la génération des packages. En production ça devrait prendre environ 48h au total, et tous les cas limites ont été pris en compte : tous les diagnostics fonctionnent.

Je vous propose de faire la génération des packages vendredi soir, et entre temps de finir les US #487 et #488, ainsi que la notice explicative dont le contenu a été vu en affinage : 
- liste des communes 
- carte des communes
- date de production des packages
- source de données de la liste des communes au RNU
- note sur l'absence de données d'imperméabilisation / artficialisation sur certaines communes qui n'est pas un bug

Est-ce que je peux vous solliciter pour une recette demain (jeudi) après-midi ?

**Comment by Phil-Loriot** [comment]
Of course yes !!!

**Comment by alexisig** [comment]
Proposition de documents pour contextualiser chaque package :
[NOTICE_03.pdf](https://github.com/user-attac
[03.pdf](https://github.com/user-attachments/files/16267569/03.pdf)
hments/files/16267557/NOTICE_03.pdf)

**Comment by Phil-Loriot** [comment]
C'est toqué pour moi !!
