### ISSUE TITLE
Masquer les graphiques INSEE

### ISSUE THREAD

**Issue by smdsgn** [MTES-MCT/sparte#351]
Dans l'état, les 4 graphiques relatifs aux données de l'INSEE manquent de clarté et sont peu compréhensibles. Afin de prendre le temps de les refondre, nous souhaitons les masquer afin de ne pas polluer les utilisateurs avec des informations inutiles.

Les 4 graphiques se trouvent dans les sections suivantes de l'onglet consommation:
- Consommation d'espaces par nouvel habitant
- Consommation d'espaces par ménages

**Comment by alexisig** [comment]
Hello @inesdartiguenave, est-ce qu'on pourrait ajouter un peu plus d'infos sur les critiques qui ont été faites sur ces graphiques sur cette US ?
