### ISSUE TITLE
Indiquer dans notre documentation notre méthode de calcul de la couche artif

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#392]
Une fois #389  et #390 terminés, dire que nous utilisons les seuils recommandées par cette fiche : https://artificialisation.developpement-durable.gouv.fr/mesurer-lartificialisation-avec-locsge/acceder-aux-analyses-realisees-partir-des-donnees-ocsge

**Comment by alexisig** [comment]
Documentation en brouillon à valider : 
- [Utilisez-vous les seuils officiels de classification de l'artificialisation ?](https://app.crisp.chat/website/0ac14c43-849c-4fc4-8e09-923b78e9a0de/helpdesk/draft/fr/9655abe7-e482-4943-a4c7-f61139e1e43a/)
- [Comment est calculée l'artificialisation](https://app.crisp.chat/website/0ac14c43-849c-4fc4-8e09-923b78e9a0de/helpdesk/draft/fr/32dd1a5a-8905-42e4-aac6-f7700248f2c9/)

**Comment by alexisig** [comment]
@Phil-Loriot @JeremieSeguin j'ai fait une proposition d'entrées dans le helpdesk pour accompagner la MEP de la nouvelle méthode de calcul de l'artif. Est-ce que vous pouvez y jeter un oeil et faire un retour / les modifier ?

**Comment by Phil-Loriot** [comment]
ça me va oui, dès que ça sera fait. Au passage, nous avons eu un retour indirect (via Pascal Lory) sur le fait que nous utilisions encore l'ancienne définition

**Comment by JeremieSeguin** [comment]
Pareil, nickel ! 

Est-ce qu'un lien vers ces questions de la FAQ est prévu sur la plateforme ?
