### ISSUE TITLE
Corriger les caractères spéciaux de la table Cerema

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#420]
Certains caractères speciaux ne passent pas, par exemple : 
![image](https://github.com/MTES-MCT/sparte/assets/16051000/c982da77-9420-4544-87ad-46add3af8f76)

**Comment by smdsgn** [comment]
Ce n'est pas spécifique aux exports. Exemple dans le diag du Gers:
![Image](https://github.com/MTES-MCT/sparte/assets/16525551/5b13e659-1d4c-4510-a345-7adb26488d20

On dirait que le problème survient lorsqu'un group_name est passé à get_cerema_cities()
