### ISSUE TITLE
Diagnostic de consommation d'ENAF - Ajouter les consommation annuelles par communes

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#434]
Pour tous les territoires dont la maille est supérieure ou égale à l'EPCI, 

Dans l'onglet Consommation > Section Consommation d'espace annuelle sur le territoire 

**Graphique :** 
Par défaut, l'évolution de la consommation annuelle de tout le territoire est représentée sous forme d'histogramme. 

Permettre de sélectionner l'échelle d'analyse (avant on appelait ça la maille) à des mailles inférieures pour faire apparaitre l'évolution de la consommation par EPCI ou par commune (garder le format histogramme) 

**Détails données et calcul** 

L'idée est de permettre aux gens de comprendre comment les sous territoires impactent la consommation du territoire diagnostiqué. 

Reporter l'évolution de la consommation d'ENAF annuelle de toutes les communes dans le tableau en les classant par Département > SCoT > EPCI 

S'inspirer de l'image ci-dessous avec l'analogie suivante : 

- 1 et 2 serait le niveau départemental, 
- 1.1, 1.2, 2.1, 2.2 serait le niveau SCoT (donc mettre nom des SCoT // et ne pas mettre les chiffres)
- 1.1.1, 1.1.2, 1.2.1, 1.2.2 ... serait le niveau des EPCI  (donc mettre nom des EPCI // et ne pas mettre les chiffres)
- 1.1.1.1 , 1.1.1.2, 1.1.2.1, 1.1.2.2 serait le niveau des communes (donc mettre nom des communes // et ne pas mettre les chiffres)

![Image](https://github.com/MTES-MCT/sparte/assets/117758546/ac19e0e6-f1fb-4188-bc06-8bb38612c222)

<img width="1252" alt="image" src="https://github.com/MTES-MCT/sparte/assets/16051000/8a5efb3f-5b2f-4fa4-bd75-0cd7183323e3">

**Comment by JeremieSeguin** [comment]
@Phil-Loriot  et @inesdartiguenave : Une US pour redonner de la visibilité sur la consommation annuelle des territoires imbriqués au territoire diagnostiqué.

Utile par exemple pour savoir quels EPCI consomme le plus dans un SCoT et quels communes consomment le plus dans ces EPCI ...  

arrivez-vous à la comprendre ainsi ?

**Comment by Phil-Loriot** [comment]
Ca me va oui. C'est clair et ça me semble utile

**Comment by smdsgn** [comment]
Dans un premier temps on remet le détail de la consommation de la maille d'analyse dans le détail des données. Ça vous va ?

Exemple pour le diag du gers:
![Image](https://github.com/MTES-MCT/sparte/assets/16525551/f25c1eeb-6597-4c41-a7ca-db907847612d)

**Comment by JeremieSeguin** [comment]
Yes, top !
