### ISSUE TITLE
Rapport triennal : ajouter la conso de la commune du diagnostic dans la tableau de conso des territoires voisins

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#435]
Dans le rapport triennal, 

1° La consommation des espaces naturels, agricoles et forestiers 

### rubrique :  Consommation annuelle des territoires voisins

Ajouter dans le tableau : 

la consommation annuelle d'espace du [Nom territoire] 

ℹ️ Les utilisateurs peuvent la trouver dans la rubrique donnée en page 5 mais pas pratique pour comparer

### rubrique : Consommation relative à la surface 

Ajouter dans le tableau : 

La consommation proportionnelle d'espace de [Nom territoire] 

ℹ️ : là pour le coup, elle n'est dans le document que dans le graphique, difficilement lisible. 

Cf. Image : Il manque les données dans le tableau pour Riorges (territoire rouge) 

![Image](https://github.com/MTES-MCT/sparte/assets/117758546/f25641d4-3f77-4984-a660-aa1e0e2d4908)

**Comment by JeremieSeguin** [comment]
@Phil-Loriot et @inesdartiguenave : Une utilisatrice nous a fait remarquer que dans la Rubrique comparaison avec les territoires voisin, le tableau comparatif ne contient pas la donnée du territoire diagnostiqué. 

Arrivez-vous comprendre cette US ainsi ?

**Comment by Phil-Loriot** [comment]
Oui, c'est un bug
