### ISSUE TITLE
DUMP des infos de la plateforme vers BREVO

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#436]
Suite à l'US #313 : faire un dump des données de la plateforme pour mettre à jour tous les contacts brevo

**Comment by JeremieSeguin** [comment]
@leabouche et @alexisig, top d'avoir priorisé cette US. 
Le niveau de priorité me va bien. 

Quelques éléments du pourquoi : 

**Priorité basse : ** 
Cette US permettait de mieux segmenter nos utilisateurs sur BREVO. Cela concernait 4893 utilisateurs en juillet qui ont téléchargé un diag ou créé un compte. 
Nous sommes en Octobre et 9120 utilisateurs sont maintenant comptabilisés sur BREVO soit 2x plus par rapport à Juillet (dont 1200 créations de compte). 
Conclusion, en 3 mois on a doublé notre nombre d'utilisateurs. A ce rythme, ça n'est pas très grave de passer "à côté" des  4893 utilisateurs "moins connus". 

**Garder le DUMP en tête : **
Le DUMP pour les 4893 utilisateurs ne concerne pas seulement les départements diagnostiqués mais aussi des informations stratégiques comme le DU_EN_COURS ou la COMPETENCE urba ... cela peut être très utile pour des communications ciblées.

**Comment by alexisig** [comment]
Remplacé par #667
