### ISSUE TITLE
Graphique de l'imperméabilisation 

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#458]
### A l'image du graphique "évolution de l'artificialisation 

<img width="828" alt="Capture d’écran 2024-06-21 à 14 42 56" src="https://github.com/MTES-MCT/sparte/assets/84960477/22aa2aa4-7637-44f1-be90-f457b07822be">

### Créer le graphique "évolution de l'imperméabilisation

Indicateurs sur la période 
- imperméabilisation 
- désimperméabilisation
- imperméabilisation nette 

### Calcul de l'imperméabilisation 

CS 1.1 Surfaces anthropisées uniquement. Sans prendre en compte CS 2.2 végétation non ligneuse

<img width="1135" alt="Capture d’écran 2024-06-21 à 14 43 58" src="https://github.com/MTES-MCT/sparte/assets/84960477/420c7c04-08cc-4011-bda7-020f22c14114">

**Comment by alexisig** [comment]
@inesdartiguenave où irait ce graphique ? Je ne le vois pas dans le [template du rapport local](https://docs.google.com/document/d/1enXF3iqHOtyU1FMDL7jVPT_IlHkyFtyc/edit)

**Comment by inesdartiguenave** [comment]
@alexisig Je viens de l'ajouter pour demander à la DGALN

**Comment by inesdartiguenave** [comment]
@alexisig trame de rapport MAJ avec le graphique p.17 

<img width="739" alt="Capture d’écran 2024-06-26 à 12 04 24" src="https://github.com/MTES-MCT/sparte/assets/84960477/336e85bb-d0d4-4732-a589-b414c484e780">

https://docs.google.com/document/d/1enXF3iqHOtyU1FMDL7jVPT_IlHkyFtyc/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**Comment by Phil-Loriot** [comment]
Pour l'encadré en tête d'onglet, mettre : 
Le [Décret n° 2023-1096 du 27 novembre 2023 relatif à l'évaluation et au suivi de l'artificialisation des sols](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000048465959) précise que le rapport relatif à l'artificialisation des sols prévu à l'article L. 2231-1 présente, pour les années civiles sur lesquelles il porte et au moins tous les trois ans, les indicateurs et données suivants :
« 1° La consommation des espaces naturels, agricoles et forestiers, exprimée en nombre d'hectares, le cas échéant en la différenciant entre ces types d'espaces, et en pourcentage au regard de la superficie du territoire couvert. Sur le même territoire, le rapport peut préciser également la transformation effective d'espaces urbanisés ou construits en espaces naturels, agricoles et forestiers du fait d'une renaturation ; 
« 2° Le solde entre les surfaces artificialisées et les surfaces désartificialisées, telles que définies dans la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme ](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid); 
**« 3° Les surfaces dont les sols ont été rendus imperméables, au sens des 1° et 2° de la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme ](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid);**
« 4° L'évaluation du respect des objectifs de réduction de la consommation d'espaces naturels, agricoles et forestiers et de lutte contre l'artificialisation des sols fixés dans les documents de planification et d'urbanisme. Les documents de planification sont ceux énumérés au [III de l'article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid). 

L’imperméabilisation des sols est donc définie comme :
1° Surfaces dont les sols sont imperméabilisés en raison du bâti (constructions, aménagements, ouvrages ou installations).
2° Surfaces dont les sols sont imperméabilisés en raison d'un revêtement (artificiel, asphalté, bétonné, couvert de pavés ou de dalles).

Au niveau national, l’imperméabilisation est mesurée par l'occupation des sols à grande échelle (OCS GE), en cours d'élaboration, dont la production sera engagée sur l'ensemble du territoire national d'ici mi 2025.

Ajouter la matrice avec juste les 2 premières colonnes en rouge

**Comment by alexisig** [comment]
@Phil-Loriot je déplace ton texte vers la discussion : #461
