### ISSUE TITLE
Grandes familles de couverture des sols des surfaces imperméabilisées

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#459]
### A l'image du graphique "évolution de l'artificialisation

<img width="1238" alt="Capture d’écran 2024-06-21 à 14 47 38" src="https://github.com/MTES-MCT/sparte/assets/84960477/d1abba9a-3585-477b-8abd-ba233a3cd1b9">

### Créer le graphique "évolution de l'imperméabilisation

Remplacer artificialisation par imperméabilisation (avec calcul ci-dessous)
Retirer C2.1 avec la formation herbacée

Proposer les 2 visualisations sur la période : 
- répartition des surfaces (graphique de gauche)
- évolution par type de surface (graphique de droite)
 
### Calcul de l'imperméabilisation

CS 1.1 Surfaces anthropisées uniquement. Sans prendre en compte CS 2.2 végétation non ligneuse

<img width="1135" alt="Capture d’écran 2024-06-21 à 14 43 58" src="https://github.com/MTES-MCT/sparte/assets/84960477/e7f208fd-a63c-4dd6-8101-fc82cdd87569">

**Comment by alexisig** [comment]
Merci pour l'US @inesdartiguenave.
Petite précision sur le croisement de matrice de l'imperméabilisation : 

![Image](https://github.com/MTES-MCT/sparte/assets/16051000/008b7ed9-f839-4d97-81c8-7eab62e472f3)

Donc sur les graphiques il n'y aurait que CS1.1.1.1 (zones bâties) et CS1.1.1.2 (zones non bâties)

**Comment by inesdartiguenave** [comment]
@alexisig j'ai MAJ la trame de rapport locale en gardant uniquement les CS 1.1.1

<img width="1238" alt="surfaces" src="https://github.com/MTES-MCT/sparte/assets/84960477/392325be-0869-458d-9194-d3054ba98093">

https://docs.google.com/document/d/1enXF3iqHOtyU1FMDL7jVPT_IlHkyFtyc/edit?usp=sharing&ouid=107690444989310422470&rtpof=true&sd=true

**Comment by alexisig** [comment]
Top merci @inesdartiguenave ! 
On a déjà des exemples de graphiques prêts si tu veux t'en servir dans la trame : #474

**Comment by Phil-Loriot** [comment]
pour l'encadré en tête du nouvel onglet : 

Le [Décret n° 2023-1096 du 27 novembre 2023 relatif à l'évaluation et au suivi de l'artificialisation des sols](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000048465959) précise que le rapport relatif à l'artificialisation des sols prévu à l'article L. 2231-1 présente, pour les années civiles sur lesquelles il porte et au moins tous les trois ans, les indicateurs et données suivants :
« 1° La consommation des espaces naturels, agricoles et forestiers, exprimée en nombre d'hectares, le cas échéant en la différenciant entre ces types d'espaces, et en pourcentage au regard de la superficie du territoire couvert. Sur le même territoire, le rapport peut préciser également la transformation effective d'espaces urbanisés ou construits en espaces naturels, agricoles et forestiers du fait d'une renaturation ; 
« 2° Le solde entre les surfaces artificialisées et les surfaces désartificialisées, telles que définies dans la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme ](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid); 
**« 3° Les surfaces dont les sols ont été rendus imperméables, au sens des 1° et 2° de la nomenclature annexée à l'[article R. 101-1 du code de l'urbanisme ](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid);** 
« 4° L'évaluation du respect des objectifs de réduction de la consommation d'espaces naturels, agricoles et forestiers et de lutte contre l'artificialisation des sols fixés dans les documents de planification et d'urbanisme. Les documents de planification sont ceux énumérés au [III de l'article R. 101-1 du code de l'urbanisme](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006074075&idArticle=LEGIARTI000045729062&dateTexte=&categorieLien=cid). 

L’imperméabilisation des sols est donc définie comme :
1° Surfaces dont les sols sont imperméabilisés en raison du bâti (constructions, aménagements, ouvrages ou installations).
2° Surfaces dont les sols sont imperméabilisés en raison d'un revêtement (artificiel, asphalté, bétonné, couvert de pavés ou de dalles).

Au niveau national, l’imperméabilisation est mesurée par l'occupation des sols à grande échelle (OCS GE), en cours d'élaboration, dont la production sera engagée sur l'ensemble du territoire national d'ici mi 2025.

**Ajouter la matrice avec juste les 2 premières colonnes en rouge**
