### ISSUE TITLE
Feedbacks Jérémie: Export Rapport local

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#512]
Section "Quelles sont les sources d'informations disponibles pour ce rapport ?"

P.4  : Dans le tableau, pour le texte "art. L. 153-27 du code de l’urbanisme" insérer le lien https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043977819

P.6 Dans le titre est "Consommation d'espace à [nom territoire] entre 2011 et 2022 " 
~~**->  remplacer par "Consommation d'espace du territoire "[nom territoire]" entre x et y"**~~
**->  remplacer par "Consommation d'espaces du territoire "[nom territoire]" entre x et y"** (validé en affinage)

P.13 : Consommation relative à la surface 
Dans cet encart il y a la phrase "se comparer" comme si c'était une consommation personnelle. Je pense qu'il faudrait plutôt la comparer avec celle des autres territoires : 
Remplacer "Cet indicateur permet de mesurer l’intensité de la consommation, par rapport à la superficie totale du territoire, et de se comparer avec les territoires similaires." par ~~"Cet indicateur permet de mesurer l’intensité de la consommation, par rapport à la superficie totale du territoire, **et de comparer cette intensité avec celle des territoires **voisins** similaires."**~~ "Cet indicateur permet de mesurer l’intensité de la consommation par rapport à la superficie totale du territoire, et de comparer avec les territoires similaires."  (validé en affinage)

**Comment by alexisig** [comment]
@JeremieSeguin est-ce que tu peux splitter ton US en plusieurs US s'il te plait ?

**Comment by alexisig** [comment]
> P.6 Dans le titre est "Consommation d'espace à [nom territoire] entre 2011 et 2022 "
-> remplacer par "Consommation d'espace de [nom territoire] entre 2011 et 2022 "

Pour ce point, pour éviter d'avoir un article par territoire (par exemple pour "en martinique" "de l'Auvergne Rhone Alpes" etc ...), on pourrait utiliser la formule "Consommation d'espace du territoire "[nom territoire]" entre x et y". Qu'est-ce que tu en penses ?

**Comment by smdsgn** [comment]
@JeremieSeguin Il manque une partie de l'US non ? La dernière phrase ne semble pas complète.

**Comment by JeremieSeguin** [comment]
> @JeremieSeguin Il manque une partie de l'US non ? La dernière phrase ne semble pas complète.

C'est une coquille je pense, je suis retourné sur cette section dans le rapport local, RAS. 
Désolé

**Comment by smdsgn** [comment]
> > [@JeremieSeguin](https://github.com/JeremieSeguin) Il manque une partie de l'US non ? La dernière phrase ne semble pas complète.
> 
> C'est une coquille je pense, je suis retourné sur cette section dans le rapport local, RAS. Désolé

Pas de souci, merci pour tes retours.
