### ISSUE TITLE
Problème de représentation : les cartes chloroplèthes représentent des données absolues

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#515]
Situation

En principe, sémiologiquement les données absolues sont à représenter par des points, et les données relatives à la surface sont à representer en aplat de couleur ([carte choroplèthe]).(https://fr.wikipedia.org/wiki/Carte_choropl%C3%A8the).

Une carte en aplat de couleur ne représente pas correctement des données absolues car la surface des aplats est généralement linéairement corrélée à la variable representée. Par exemple sur la carte de consommation : 
![image](https://github.com/MTES-MCT/sparte/assets/16051000/8a12383f-58c8-4434-bbfb-3c86a087260c)

Les plus petites communes sont en blanc, et les plus grandes en bleu. L'intensité de consommation d'espace n'est pas lisible.

Solution

Remplacer les cartes choroplèthes avec des données absolues par des données relatives à la surface.

----

Cartes concernées : 
- theme_map_conso
- theme_map_artif

---- 
Exemple de correction pour le gers : 
Avant
![image](https://github.com/MTES-MCT/sparte/assets/16051000/2db72d84-518a-4baa-8f65-b3cb78832485)

Après (en pour mille)
![image](https://github.com/MTES-MCT/sparte/assets/16051000/0ad5c8b7-68a4-4251-b5d6-dac61efff345)

**Comment by leabouche** [comment]
@alexisig @smdsgn Il semblerait que cette modif ait été faite sur les images statiques du diagnostic uniquement, lorsqu'on ouvre la carte de conso ce sont les données absolues qui sont affichées
