### ISSUE TITLE
Ajout nouvelles données OCS GE publiées 

### ISSUE THREAD

**Issue by inesdartiguenave** [MTES-MCT/sparte#530]
### Situation actuelle 

17 départements avec OCS GE sur Mon Diag Artif

### Situation souhaitée

36 départements disponibles (dont déjà 30 en ligne sur les Géoservices)

https://geoservices.ign.fr/ocsge#:~:text=L%E2%80%99OCS%20GE%20est%20une%20base%20de%20donn%C3%A9es%20de,m%C3%A9tropolitain%20et%20des%20d%C3%A9partements%20et%20r%C3%A9gions%20d%E2%80%99outre-mer%20%28DROM%29
.

**Comment by inesdartiguenave** [comment]
@alexisig pourrais tu sizer l'issue pour la prochaine priorisation ?

**Comment by inesdartiguenave** [comment]
#355

**Comment by alexisig** [comment]
Fermé car mis en place avec #536
