### ISSUE TITLE
Ajouter les crédits OpenStreetMap

### ISSUE THREAD

**Issue by lmagreault** [MTES-MCT/sparte#579]
Quand le fond de plan OpenStreetMap est utilisé, il est nécessaire de le créditer correctement.
Voir : https://www.openstreetmap.org/copyright

Exemple : 
![image](https://github.com/user-attachments/assets/5f947323-8015-43c4-bc80-ef4df449214f)
![image](https://github.com/user-attachments/assets/5aaa48bb-462c-4a12-9d30-994134e65a2a)

**Comment by alexisig** [comment]
Merci pour l'info @lmagreault, on change ça rapidement !

**Comment by Jean-BaptisteC** [comment]
Bonjour, est ce qu'un hyperlien est présent vers la page copyright ?

**Comment by alexisig** [comment]
@Jean-BaptisteC non en effet, on va aussi rajouter ça 👍
