### ISSUE TITLE
Lien vers FAQ mort

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#584]
Tous les liens "qu'est-ce qu'un millésime" de l'onglet Artificialisation sont "morts". 

Les liens pointent vers : https://faq.mondiagartif.beta.gouv.fr/fr/fr/article/quest-ce-quun-millesime-110ihlr/
Au lieu de : https://faq.mondiagartif.beta.gouv.fr/fr/article/quest-ce-quun-millesime-110ihlr/

(il y a un "fr/" en trop).

**Comment by alexisig** [comment]
@smdsgn pour information j'ai passé la valeur `FAQ_URL` de `https://faq.mondiagartif.beta.gouv.fr/fr/` à `https://faq.mondiagartif.beta.gouv.fr/`

**Comment by JeremieSeguin** [comment]
Top, merci !
