### ISSUE TITLE
[METABASE | BUG] Différence de résultat entre le regroupement par "Territory Name" et par "Land_ID"

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/sparte#593]
Hello,

Voici le problème rencontré en vidéo: https://www.loom.com/share/6470299dd09d4f32b012993b11ae6eb1?sid=bdffd6c2-be7e-4be2-baa2-5e71a78e134d

**Comment by alexisig** [comment]
Hello @NicolasM92, il y a environ 4000 communes avec des homonymes en France, donc si tu fais un `distinct` sur le nom des territoires tu auras un total plus faible que si tu fais un distinct sur leur clef primaire (`land_id`)

**Comment by NicolasM92** [comment]
Ah effectivement! 
Ok très clair, mais du coup comment expliquer le nombre plus important de rapports locaux par communes au RNU distinctes vs le nombre de communes au RNU au total ?

**Comment by NicolasM92** [comment]
Je crois que je sais d'où vient le problème @alexisig, je creuse et reviens vers toi

**Comment by NicolasM92** [comment]
Non au final j'avais l'impression que les jointures étaient mauvaises mais je retombe sur le même résultat en corrigeant @alexisig

**Comment by alexisig** [comment]
@NicolasM92 est-ce que tu peux poster un lien de la question sur metabase ?

**Comment by NicolasM92** [comment]
Yes [la voici](https://sparte-metabase.osc-secnum-fr1.scalingo.io/question#eyJuYW1lIjoiTm9tYnJlIGRlIGNvbW11bmVzIGRpc3RpbmN0ZXMgcG91ciBsZXNxdWVsbGVzIHVuIHJhcHBvcnQgbG9jYWwgYSDDqXTDqSB0w6lsw6ljaGFyZ8OpIiwiZGVzY3JpcHRpb24iOm51bGwsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjIsInF1ZXJ5Ijp7ImFnZ3JlZ2F0aW9uIjpbWyJkaXN0aW5jdCIsWyJmaWVsZCIsIkRpYWdub3N0aWNzIC0gUHJvamVjdF9fbGFuZF9pZCIseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV1dXSwiZmlsdGVyIjpbIj0iLFsiZmllbGQiLCJkdV9vcHBvc2FibGUiLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCJSTlUiXSwic291cmNlLXF1ZXJ5Ijp7ImJyZWFrb3V0IjpbWyJmaWVsZCIsMjE0LHsiYmFzZS10eXBlIjoidHlwZS9CaWdJbnRlZ2VyIn1dLFsiZmllbGQiLDk3Nyx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJQdWJsaWMgRGF0YSBTdWRvY3VoIC0gSW5zZWUifV0sWyJmaWVsZCIsOTgzLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIFN1ZG9jdWggLSBJbnNlZSJ9XSxbImZpZWxkIiwxMDczLHsiYmFzZS10eXBlIjoidHlwZS9Cb29sZWFuIiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIFN1ZG9jdWhlcGNpIC0gU291cmNlIn1dLFsiZmllbGQiLDQ5Myx7ImJhc2UtdHlwZSI6InR5cGUvRGF0ZVRpbWVXaXRoTG9jYWxUWiIsImpvaW4tYWxpYXMiOiJNZXRhYmFzZSBTdGF0ZGlhZ25vc3RpYyIsInRlbXBvcmFsLXVuaXQiOiJtb250aCJ9XSxbImZpZWxkIiw0OTUseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiTWV0YWJhc2UgU3RhdGRpYWdub3N0aWMifV0sWyJmaWVsZCIsNDg4LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6Ik1ldGFiYXNlIFN0YXRkaWFnbm9zdGljIn1dLFsiZmllbGQiLDQ3OSx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJNZXRhYmFzZSBTdGF0ZGlhZ25vc3RpYyJ9XSxbImZpZWxkIiwxNjgseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiRGlhZ25vc3RpY3MgLSBQcm9qZWN0In1dLFsiZmllbGQiLDIwNCx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJEaWFnbm9zdGljcyAtIFByb2plY3QifV0sWyJmaWVsZCIsOTY5LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IkRpYWdub3N0aWNzIC0gUHJvamVjdCJ9XV0sImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsMTAxNCx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XSwicmFwcG9ydC1sb2NhbCJdLFsiPSIsWyJmaWVsZCIsMTY4LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IkRpYWdub3N0aWNzIC0gUHJvamVjdCJ9XSwiQ09NTVVORSIsIkNPTU0iXV0sImpvaW5zIjpbeyJhbGlhcyI6Ik1ldGFiYXNlIFN0YXRkaWFnbm9zdGljIiwiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDIxMyx7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciJ9XSxbImZpZWxkIiw0ODUseyJiYXNlLXR5cGUiOiJ0eXBlL0JpZ0ludGVnZXIiLCJqb2luLWFsaWFzIjoiTWV0YWJhc2UgU3RhdGRpYWdub3N0aWMifV1dLCJzb3VyY2UtdGFibGUiOjUzLCJzdHJhdGVneSI6ImxlZnQtam9pbiJ9LHsiYWxpYXMiOiJEaWFnbm9zdGljcyAtIFByb2plY3QiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMjEzLHsiYmFzZS10eXBlIjoidHlwZS9CaWdJbnRlZ2VyIn1dLFsiZmllbGQiLDE3Myx7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciIsImpvaW4tYWxpYXMiOiJEaWFnbm9zdGljcyAtIFByb2plY3QifV1dLCJzb3VyY2UtdGFibGUiOjUxLCJzdHJhdGVneSI6ImxlZnQtam9pbiJ9LHsiYWxpYXMiOiJQdWJsaWMgRGF0YSBDb21tdW5lIC0gVGVycml0b3J5IE5hbWUiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMjA0LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IkRpYWdub3N0aWNzIC0gUHJvamVjdCJ9XSxbImZpZWxkIiwzMjcseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiUHVibGljIERhdGEgQ29tbXVuZSAtIFRlcnJpdG9yeSBOYW1lIn1dXSwic291cmNlLXRhYmxlIjozMCwic3RyYXRlZ3kiOiJsZWZ0LWpvaW4ifSx7ImFsaWFzIjoiUHVibGljIERhdGEgU3Vkb2N1aCAtIEluc2VlIiwiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDMzMix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJQdWJsaWMgRGF0YSBDb21tdW5lIC0gVGVycml0b3J5IE5hbWUifV0sWyJmaWVsZCIsOTczLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIFN1ZG9jdWggLSBJbnNlZSJ9XV0sInNvdXJjZS10YWJsZSI6NjQsInN0cmF0ZWd5IjoibGVmdC1qb2luIn0seyJhbGlhcyI6IlB1YmxpYyBEYXRhIEVwY2kgLSBFcGNpIiwiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDMyOCx7ImJhc2UtdHlwZSI6InR5cGUvQmlnSW50ZWdlciIsImpvaW4tYWxpYXMiOiJQdWJsaWMgRGF0YSBDb21tdW5lIC0gVGVycml0b3J5IE5hbWUifV0sWyJmaWVsZCIsMzc3LHsiYmFzZS10eXBlIjoidHlwZS9CaWdJbnRlZ2VyIiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIEVwY2kgLSBFcGNpIn1dXSwic291cmNlLXRhYmxlIjozNiwic3RyYXRlZ3kiOiJsZWZ0LWpvaW4ifSx7ImFsaWFzIjoiUHVibGljIERhdGEgU3Vkb2N1aGVwY2kgLSBTb3VyY2UiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMzc1LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIEVwY2kgLSBFcGNpIn1dLFsiZmllbGQiLDEwNzgseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiUHVibGljIERhdGEgU3Vkb2N1aGVwY2kgLSBTb3VyY2UifV1dLCJzb3VyY2UtdGFibGUiOjY2LCJzdHJhdGVneSI6ImxlZnQtam9pbiJ9XSwic291cmNlLXRhYmxlIjozM319LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InNjYWxhciIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5jZWxsX2NvbHVtbiI6InJlcXVlc3RlZF9kb2N1bWVudCIsInRhYmxlLnBpdm90X2NvbHVtbiI6ImRvbmUifSwib3JpZ2luYWxfY2FyZF9pZCI6MTY0fQ==)

**Comment by alexisig** [comment]
Est-ce que tu peux partager la question où le second problème que tu mentionnes est présent ?
> [...] du coup comment expliquer le nombre plus important de rapports locaux par communes au RNU distinctes vs le nombre de communes au RNU au total ?

**Comment by NicolasM92** [comment]
C'est la question précédente en comparaison avec [celle-ci](https://sparte-metabase.osc-secnum-fr1.scalingo.io/question#eyJuYW1lIjoiTm9tYnJlIGRlIGNvbW11bmVzIiwiZGVzY3JpcHRpb24iOm51bGwsImRhdGFzZXRfcXVlcnkiOnsiZGF0YWJhc2UiOjIsInF1ZXJ5Ijp7ImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdXSwiZmlsdGVyIjpbIj0iLFsiZmllbGQiLDk3Nyx7ImpvaW4tYWxpYXMiOiJQdWJsaWMgRGF0YSBTdWRvY3VoIC0gSW5zZWUifV0sIlJOVSJdLCJqb2lucyI6W3siYWxpYXMiOiJQdWJsaWMgRGF0YSBTdWRvY3VoIC0gSW5zZWUiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMzMyLHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLFsiZmllbGQiLDk3Myx7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCIsImpvaW4tYWxpYXMiOiJQdWJsaWMgRGF0YSBTdWRvY3VoIC0gSW5zZWUifV1dLCJmaWVsZHMiOiJhbGwiLCJzb3VyY2UtdGFibGUiOjY0LCJzdHJhdGVneSI6ImxlZnQtam9pbiJ9LHsiYWxpYXMiOiJQdWJsaWMgRGF0YSBFcGNpIC0gRXBjaSIsImNvbmRpdGlvbiI6WyI9IixbImZpZWxkIiwzMjgseyJiYXNlLXR5cGUiOiJ0eXBlL0JpZ0ludGVnZXIifV0sWyJmaWVsZCIsMzc3LHsiYmFzZS10eXBlIjoidHlwZS9CaWdJbnRlZ2VyIiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIEVwY2kgLSBFcGNpIn1dXSwiZmllbGRzIjoiYWxsIiwic291cmNlLXRhYmxlIjozNiwic3RyYXRlZ3kiOiJsZWZ0LWpvaW4ifSx7ImFsaWFzIjoiUHVibGljIERhdGEgU3Vkb2N1aGVwY2kgLSBTb3VyY2UiLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMzc1LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0Iiwiam9pbi1hbGlhcyI6IlB1YmxpYyBEYXRhIEVwY2kgLSBFcGNpIn1dLFsiZmllbGQiLDEwNzgseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQiLCJqb2luLWFsaWFzIjoiUHVibGljIERhdGEgU3Vkb2N1aGVwY2kgLSBTb3VyY2UifV1dLCJmaWVsZHMiOiJhbGwiLCJzb3VyY2UtdGFibGUiOjY2LCJzdHJhdGVneSI6ImxlZnQtam9pbiJ9XSwic291cmNlLXRhYmxlIjozMH0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5Ijoic2NhbGFyIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fSwib3JpZ2luYWxfY2FyZF9pZCI6MTQyfQ==).

**Comment by alexisig** [comment]
Est-ce qu'on peut fermer cette issue @NicolasM92 ? Le problème qu'il restait est sur #597 ?
