### ISSUE TITLE
Metabase | Bug : Croisement BDD sudocuh & sudocuh_epci ne semblent pas fonctionnels sur les EPCI

### ISSUE THREAD

**Issue by NicolasM92** [MTES-MCT/sparte#597]
Hello Alex,

Voici une [vidéo explicative](https://www.loom.com/share/76807838048349d9812ee88d4bb389e9?sid=a0b217a3-f665-4227-87f3-2e92807d631b) du problème et l'URL de la [question](https://sparte-metabase.osc-secnum-fr1.scalingo.io/question/180-nombre-depci-distincts-diagnostiques-sur-mondiagartif).

**Comment by alexisig** [comment]
@NicolasM92 est-ce que tu peux poster le lien où je peux reproduire l'erreur de la vidéo stp ?
