### ISSUE TITLE
Changer le type de valeur du champ LAST_DPT_DIAGNOSTIC de entier à string

### ISSUE THREAD

**Issue by alexisig** [MTES-MCT/sparte#626]
Le champs est utilisé pour conserver l'identifiant du département du dernier diagnostic téléchargé par un utilisateur sur brevo.

Problème : la valeur du code département est un string car elle peut contenir des lettres (cas de la corse), et pour les départements dont le code est inférieur à 10, pour lesquels un 0 est toujours présent au début. Dans le cas où le diagnostic est fait sur plusieurs départements, un string de ce format est retourné : "35,56"

Solution : contacter le support brevo pour migrer le type de ce champs d'entier à string.

**Comment by alexisig** [comment]
lié à #589

**Comment by alexisig** [comment]
@JeremieSeguin je pense que c'est pas quelque chose qui peut être fait facilement en autonomie de votre côté (les requêtes à faire sur metabase seraient complexes), et on va pas avoir le temps côté dev pour le faire.

est-ce que tu aurais une solution plus low-tech ?

**Comment by JeremieSeguin** [comment]
> @JeremieSeguin je pense que c'est pas quelque chose qui peut être fait facilement en autonomie de votre côté (les requêtes à faire sur metabase seraient complexes), et on va pas avoir le temps côté dev pour le faire.
> 
> est-ce que tu aurais une solution plus low-tech ?

Peut-être via [cette US](https://github.com/MTES-MCT/sparte/issues/436) ?  
Autrement hormis via METABASE je n'ai pas d'idée pour récupérer les données en base et les déposer sur Brevo.

**Pour info :** 
- J'ai modifié le type de LAST_DPT_DIAGNOSTIC en texte et j'ai mis à jour la base de contact BREVO avec les valeurs de l'ancien attribut LAST_DPT_DIAGNOSTIC (qui était un nombre). Le champs est toujours vide pour les utilisateurs de Corse et ceux dont l'utilisation de l'app date d'avant la mise en place de cet attribut. 
- J'ai modifié le type de A_TELECHARGE_RAPPORT_TRIENNAL en texte. Il est vide pour tous les utilisateurs. 

**Pourquoi cette US ?**
Aujourd'hui l'OCS GE a été intégrée pour la Corse du Sud. Je ne peux pas tenir informé nos utilisateurs/utilisatrices.

**Comment by alexisig** [comment]
@JeremieSeguin Top que tu aies pu corriger `LAST_DPT_DIAGNOSTIC` directement depuis brevo !

Pour le dump, c'est un effort important pour une seule occasion.

Comme on a maintenant livré tous les départements pour lesquels le bug existait, peut-être c'est ok de se dire qu'on met en place cette notification qu'à partir des prochains départements ?

**Comment by JeremieSeguin** [comment]
Yes, pourquoi pas. 
On peut fermer cette US en tout cas. Mais laisser [celle-ci](https://github.com/MTES-MCT/sparte/issues/436) en priorité basse.
