### ISSUE TITLE
Créer un graphique en barres de comparaison du taux de conso et du taux d'évolution démographique

### ISSUE THREAD

**Issue by leabouche** [MTES-MCT/sparte#672]
**Objectif**
On souhaite mettre en perspective l'évolution de la consommation d'espaces NAF d'un territoire avec l'évolution de sa population sur la même période. 
Cette comparaison permet de donner des pistes d'explications à une consommation d'espaces élevée par exemple, l'habitat étant dans la plupart des cas la destination principale de la consommation. 
On se propose également de contextualiser ces données avec des valeurs de références afin que les territoires puissent se comparer avec des mailles administratives pertinentes. 

**Graphe - Wireframe:**
![Capture d’écran 2024-10-24 à 11 28 53](https://github.com/user-attachments/assets/9d048bb0-decb-4539-9e95-d8683024a654)

**Type de graphe highchart proposé:** 
https://www.highcharts.com/demo/highcharts/column-comparison
Attention ces graphes doivent pouvoir prendre des valeurs négatives (pour l'évolution de la démo)

**Titre du graphique**
"Evolutions comparées de la population et de la consommation d'espaces NAF entre [date début période] et [date fin periode]"

**Période d'analyse**
- Les données démographiques n'étant disponible que jusqu'à 2021, on prend l'intersection entre la période d'analyse (par défaut ou choisie par l'utilisateur) et [:2021]. La période par défaut pour ce graphe sera donc: [2011; 2021]

**Valeurs affichées et légende**
Taux de consommation d'espaces NAF (_période_) : nombre d'hectares consommés sur la période d'analyse / surface du territoire (%)
Evolution démographique (_période_) : (population année fin - population année début) / population année debut (%)
Affichage persistant des valeur en % 

**Valeurs de comparaison en grisé (ou même couleur avec opacité réduite)**
- Pour les communes : Médianes (consommation + évolution démographique) des communes du même EPCI
Légende au hover: Valeur + "Médiane des communes de l'EPCI"

- Pour les EPCI/SCoT :  Médianes (consommation + évolution démographique) des EPCI du département
Légende au hover: Valeur + "Médiane des EPCI du département" (ou SCoT)

- Pour les départements: Médianes (consommation + évolution démographique) des départements de la région (pour la période concernée) 
Légende au hover: Valeur + "Médiane des départements de la région"

- Pour les régions : Médianes (consommation + évolution démographique) des régions françaises (pour la période concernée) 
Légende au hover: Valeur + "Médiane des régions françaises"

**Comment by alexisig** [comment]
https://jsfiddle.net/wf5k9ogj/8/

**Comment by leabouche** [comment]
Rajouter la période temporelle dans la légende, par ex: (2011-2021)

**Comment by leabouche** [comment]
J'enleverais les % sur les graduations de l'axe horizontal, mettrais plutôt "(%)" dans les légendes sur les deux barres
