### ISSUE TITLE
Créer un graphique pour visualiser la densité de population du territoire

### ISSUE THREAD

**Issue by leabouche** [MTES-MCT/sparte#674]
**Titre du graphique** : "Densité de population (2021)"

**Type de graphique** : jauge linéaire 

**Echelle du graphique** : répartir la plage de valeurs en 6 sections 

ou bien propositions suivantes selon la maille considérée: 
- Communes SCOT et EPCI
![Capture d’écran 2024-10-24 à 15 36 36](https://github.com/user-attachments/assets/ac4beb72-6f2d-49ca-8040-74bc52d7b5ef)
- Départements et régions: 
![Capture d’écran 2024-10-24 à 15 37 43](https://github.com/user-attachments/assets/4189806f-e4fd-4248-bb9c-d11452cea33b)

**Valeur affichée:** Densité = nombre d'habitants (2021) / Superficie du territoire (km2)

**Astuces de Lecture**
La densité de population est le rapport entre l’effectif de population du territoire et sa superficie. Par souci de cohérence avec le reste des indicateurs, nous avons choisi de l’exprimer en habitants par hectare. 

Avec le bouton [], vous pouvez afficher le graphique en plein écran.

Avec le bouton [], vous pouvez télécharger le graphique sous forme d'image (utilisez PNG si vous ne savez pas lequel choisir).

**Comment by alexisig** [comment]
valeur max = plus grosse densité de la typologie de territoire ?

**Comment by leabouche** [comment]
oui !
