### ISSUE TITLE
Créer un graphe qui permet de visualiser l'évolution temporelle de la population et de la conso

### ISSUE THREAD

**Issue by leabouche** [MTES-MCT/sparte#676]
**Objectif**
Permettre à l'utilisateur de comparer les tendance d'évolutions de la conso, de la conso pour l'habitat, et de la démographie afin de visualiser s'il existe une corrélation entre les deux. 

**Titre du graphe**
"Evolutions comparées de la consommation d'espaces NAF et de la population du territoire" 

**Description du graphique**

Abscisse: années de la période d'analyse

Double ordonnée:
- à gauche: consommation d'espaces NAF (ha)
- à droite : Population du territoire (hab)

Bar graph : Conso totale + habitat 
Line graph : population

Légende
Consommation d'espaces NAF totale 
Consommation d'espaces NAF à destination de l'habitat
Population

![Capture d’écran 2024-10-24 à 16 36 24](https://github.com/user-attachments/assets/69ec6031-8f8d-427c-bfeb-cefc11ca473e)

**Astuces de lecture**

**Pour ce qui concerne les données de population, il est important de noter que l’INSEE indique que “les résultats des recensements depuis 2006 ne se comparent correctement entre eux que sur des périodes espacées d’au moins 5 ans”. Les données annuelles de population affichées sur le graphe ne sont donc pas comparables d’une année sur l’autre pour mesurer précisément l’évolution de la population.** 

Vous pouvez choisir les données apparaissant sur le graphique en cliquant sur la légende. 

Avec le bouton [], vous pouvez afficher le graphique en plein écran.

Avec le bouton [], vous pouvez télécharger le graphique sous forme d'image (utilisez PNG si vous ne savez pas lequel choisir).

**Comment by alexisig** [comment]
https://jsfiddle.net/hom0cr41/2/

**Comment by leabouche** [comment]
Pour les légendes, j'enleverais aussi les unités (hab et ha) des graduations pour les mettre sur les titres des axes et/ou sur la légende

**Comment by leabouche** [comment]
Vu en affinage: 
- affichage des barres de consommations jusqu'à la dernière année disponible
- affichage de la courbe de population en trait plein jusqu'aux dernieres données disponibles (2020), en pointillés les valeurs projetées pour les années suivantes
