### ISSUE TITLE
Créer un graphe qui compare les territoires similaires par rapport à la démographie et à la conso

### ISSUE THREAD

**Issue by leabouche** [MTES-MCT/sparte#678]
Similaire au graphe de l'US #677 

Titre: "Consommation foncière au regard de l'évolution de la population pour les territoires similaires"

Positionner ce graphe à la fin de la section "Comparaison avec les territoires similaires"

Reprendre les codes couleurs spécifiques pour chaque territoire comme dans les autres graphes de la section

Wireframe
![Capture d’écran 2024-10-24 à 17 12 14](https://github.com/user-attachments/assets/f7e75421-7fd5-4657-89e5-1b0304dd8a40)

Astuces de lecture:

Ce graphique permet de mettre en relation la consommation d’espaces des territoires et leur évolution démographique sur une période donnée. Il permet de situer chaque territoire par rapport à la médiane départementale, régionale ou nationale en fonction de la maille concernée, et de visualiser sa population totale grâce à la taille des bulles. 

Vous pouvez modifier votre sélection de territoires de comparaison dans la section dédiée (plus haut sur la page) en cliquant sur “Ajouter un territoire de comparaison” ou en supprimant des territoires de la liste.

Vous pouvez également les afficher ou non sur le graphe en cliquant sur leur nom dans la légende.  

Avec le bouton [], vous pouvez afficher le graphique en plein écran.

Avec le bouton [], vous pouvez télécharger le graphique sous forme d'image (utilisez PNG si vous ne savez pas lequel choisir).

**Comment by alexisig** [comment]
https://jsfiddle.net/q01ym25c/

**Comment by leabouche** [comment]
afficher en rouge (et opacité 100%?) le territoire sur lequel le diagnostic est fait pour le faire ressortir, comme sur les autres graphes de comparaison

**Comment by leabouche** [comment]
légender que la tailles des cercles est proportionnelle à la conso
