### ISSUE TITLE
La modification de la période d'analyse ne fonctionne pas

### ISSUE THREAD

**Issue by leabouche** [MTES-MCT/sparte#688]
Bug présent uniquement sur la staging 

Bug reproduit par Alexis 

La modification de la période d'analyse ne fonctionne pas. 
- Clic sur le bouton d'édition de la période d'analyse
- Je modifie l'année de début de 2011 à 2018 > enregistrer
- Modale "la période a été mise à jour"

--> Aucun effet sur la création d'un nouveau diag et la période affichée sur l'interface reste inchangée (période par défaut 2011-2022)
Il faut recharger la page pour que la période se mette à jour 

![Capture d’écran 2024-10-28 à 12 15 02](https://github.com/user-attachments/assets/dcd3ddc4-7635-4127-a83f-eea773658f52)

_Originally posted by @leabouche in https://github.com/MTES-MCT/sparte/discussions/638#discussioncomment-10937381_

**Comment by smdsgn** [comment]
Corrigé #691
