### ISSUE TITLE
Erreurs de calcul dans les tableaux des matrices de passage de la page usage et couverture OCSGE

### ISSUE THREAD

**Issue by JeremieSeguin** [MTES-MCT/sparte#740]
Erreur remontée par utilisatrice, Cheffe de projet SCoT du Grand Amienois [Diag dispo ici](https://mondiagartif.beta.gouv.fr/project/115374/tableau-de-bord/d%C3%A9couvrir-l-ocsge) 

Erreur reproduite sur le [diag de Rennes Métropole](https://mondiagartif.beta.gouv.fr/project/115364/tableau-de-bord/d%C3%A9couvrir-l-ocsge)

**_Remontée n°1 :_** 
- Proposer des astuces de lecture pour les tableaux qui ont servi à produire les matrices de passages 

**_Remontée n°2 :_** 
- Pour US 1.1 vers US 1.1, à quoi correspondent les valeurs différentes de 0 ? 
Exp : 177,3 hectares sont passés d'usage Agriculture vers Agriculture ? 

**_Remontée n°3 :_** 
- Quelle est l'unité ? 

**_Remontée n°4 :_** 
- En comparant le graphique répartition des usages à date du dernier millésime (2021 pour le SCoT du Grand Amienois) avec les colonnes du tableau de passages, les grandeurs et les nombres ne correspondent pas 
Exp : US1 326 117 Ha pour US 1 dans le graphique contre 389,6 pour (US 1.1 + US 1.2 + US 1.3) des trois colonnes du tableau (pas le même nombre, ni la même grandeur) 

Je n'ai pas su expliquer les chiffres à notre utilisatrice. 
Elle a une réunion de présentation aux élus la semaine prochaine. 
Je lui ai dit que je reviendrais vers elle rapidement avec la validation qu'il y ait un problème ou non ..

**Comment by JeremieSeguin** [comment]
Top, merci beaucoup pour ces éclairages. 

Pour info la matrice de passage était bien comprise. Mais comme il n'était pas possible de l'extraire en dynamique pour sa présentation, notre utilisatrice s'est penchée sur le tableau et avait rencontré les problèmes mentionnés. 

Pour la remontée 2, j'imaginais la même chose. 

Je note qu'il y aurait que la remontée 4 - US 1.1 qui poserait problème.

En attente de validation par Alexis

**Comment by alexisig** [comment]
Le fix est en staging si vous voulez jeter un oeil : https://sparte-staging.osc-fr1.scalingo.io/ 
(Il n'y a que les données du 80 sur l'environnement)

**Comment by leabouche** [comment]
Je viens de jeter un oeil pour le [Diag d'amiens](https://sparte-staging.osc-fr1.scalingo.io/project/90604/tableau-de-bord/d%C3%A9couvrir-l-ocsge) et on a pas les mêmes nomenclatures dans les lignes et dans les colonnes des tableaux de données des matrices de passage. 
par ex: Matrice CS: on a 1.2.2 en colonne mais pas en ligne.

**Comment by JeremieSeguin** [comment]
Merci pour ce fix ultra rapide ! 
Ca me parait plus juste comme ça oui. 👌

Autrement comme dit Léa, quelques disparités sur les lignes et colonnes affichées dans les tableaux de passages des couvertures et des usages 

Pour quand est prévu la MEP sur la démographie ?
